### ISSUE TITLE
Support for ELMAH ?

### ISSUE THREAD

**Issue by kiquenet** [damianh/LibLog#106]

**Comment by mperdeck** [comment]
+1

I am the author of JSNLog, a package that logs client side events in the server side log. It currently uses Common.Logging, but LibLog looks like a better solution. 

However, looking at my stats, Elmah is the most popular server side logging package amongst those who use JSNLog, so Elmah support in LibLog would be critical to me.

**Comment by damianh** [comment]
@odinserj Thank you for the insight and, having looked at ELMAH, I agree with the assertion.
