### ISSUE TITLE
Serilog 2.0 context support

### ISSUE THREAD

**Issue by tmschlot** [damianh/LibLog#107]
Serilog v2 is getting rid of Serilog.FullNetFx.  (https://nblumhardt.com/2016/05/serilog-2-0-release-plans/)  This breaks how LibLog adds context to events, because it's getting the LogContext from that assembly.  (https://github.com/damianh/LibLog/blob/master/src/LibLog/LibLog.cs#L1492)  Haven't spent too much time thinking about a solution, but is there a way to support v2 without breaking support for previous versions?  

Thanks.

**Comment by petersondrew** [comment]
I see the pull request has been added - how do we go about merging this? This would break compatibility with Serilog 1.x, correct?

**Comment by damianh** [comment]
Done in https://github.com/damianh/LibLog/commit/bdb1dbf160f9968d9024f480a2a5c89f7ccf6436

Also Serilog 1.x is still supported.
