### ISSUE TITLE
Log to different log files

### ISSUE THREAD

**Issue by akshetty9** [damianh/LibLog#111]
I am logging events of all types to single Json file irrespective of LogLevel. Now I have a requirement to log some custom performance counters to a seperate Json file. How can this be done in Serilog. Should I create different Logger Instance and use that where ever I am going to Log the performance counters? Want to use this with LibLog.

**Comment by akshetty9** [comment]
Sorry. Wrong place

**Comment by damianh** [comment]
No worries.

I will say though that logging, performance metrics and auditing are
orthoganal. I would not recommend LibLog, or any other logging framework,
for perf metrics or auditing.

If your lib exposes perf metrics, create your own API to raise them and let
the consumer worry about piping them somewhere.

**Comment by akshetty9** [comment]
Thanks. WE

**Comment by akshetty9** [comment]
Thanks for your suggestion. Our application logs performance counters like Number of call/sec, Call Duration etc for different APIs and can be viwed on PerfMon. Idea was to log these counters to a separate json file so that it can be transferred to LosStash/ELK. Since we are already using Serlilog for logging we thought we can make use of it. Any thoughts on this?

**Comment by akshetty9** [comment]
thanks.
