### ISSUE TITLE
StyleCop violations - Include autogenerated comment

### ISSUE THREAD

**Issue by hastarin** [damianh/LibLog#112]
I'm using [StyleCop Analyzers](https://github.com/DotNetAnalyzers/StyleCopAnalyzers) in my project and of course it complains about all sorts in the LibLog code.

Simply adding an auto-generated comment prevents this:
`// <auto-generated/>`

I'm not sure if this would cause issues for others that may not want the code treated as auto-generated but thought I'd raise it as an issue for consideration at least.

**Comment by damianh** [comment]
+1. Wing on a PR?

**Comment by damianh** [comment]
Also, in net core / standard / whatever , the class file won't be added to your project (afaik). So maybe this will go away on it's own accord....

**Comment by hastarin** [comment]
This isn't restricted to net core/standard.   If you're happy with this addition I'm happy to spend some time to create a PR with a fix.

**Comment by damianh** [comment]
Yeah happy with that, cheers!

**Comment by damianh** [comment]
Going to close this. The new way of including source files (for new csproj) doesn't add it directly to the project so I don't think this will be a problem in the future.

Current users can just modify the file with this comment for now.
