### ISSUE TITLE
Application build for release crashes in GetCurrentClassLogger

### ISSUE THREAD

**Issue by alexeyzimarev** [damianh/LibLog#113]
Everything works when app is built for Debug but as soon as it is built for Release, `GetCurrentClassLogger` throws a null reference exception.

Is it only me or may be this is a limitation of the `StackFrame`?

**Comment by damianh** [comment]
Any change of a repro @alexeyzimarev ? No other reports yet of this yet....

(Sorry for slow response, other things and I'm holding off liblog work until netstandard & tooling have settled)

**Comment by damianh** [comment]
No repro and no other reports so closing.

Point of note: release builds do end up with different stackframe info because of optimisations.

**Comment by Marfusios** [comment]
Hello @damianh, 

one user of [websocket client](https://github.com/Marfusios/websocket-client) library reported a similar issue. 
Release build on UWP platform. I had to implement fallback and turn off logging for that situation. 

Here is a callstack: 
```
System.NullReferenceException: Object reference n ot set to an instance of an object.
  Module "Websocket.Client.Logging.LogProvider", in GetCurrentClassLogger
  Module "Websocket.Client.WebsocketClient", in .cctor
  ?
System.TypeInitializationException: A type initializer threw an exception. To determine which type, inspect the InnerException's StackTrace property.
  ?
  ?
  Module "Websocket.Client.WebsocketClient", in Start
  Module "System.Runtime.ExceptionServices.ExceptionDispatchInfo", in Throw
  ?
  ?
  ?
  Module "System.Runtime.CompilerServices.TaskAwaiter", in GetResult
  Module "MyAppUWP.ServerNotifications", in InitializeWebSocket
```
