### ISSUE TITLE
Question : Contextul Logging

### ISSUE THREAD

**Issue by akshetty9** [damianh/LibLog#115]
In Serilog I can  push multiple properties to log with following code. I am doing this in a middleware to push properties from context. How can i do this using LibLog?
Could you please let me know where can I find out more about OpenMappedContext and NestedContext

```
using (LogContext.PushProperties(
                        new PropertyEnricher(Constants.CorelationId, id),
                        new PropertyEnricher(Constants.ClientId, context.GetClientId()),
                        new PropertyEnricher(IdentityServiceConstants.RemoteIpAddress, context.Request.RemoteIpAddress)))
                {
                    await next();
                }
```

**Comment by damianh** [comment]
Hmm, yes should do more docs on this, will leave it open and do it when doing netstandard work.

You can see how MDC and NDC map to serilog here https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests.Serilog2/SerilogLogProviderLoggingTests.cs#L99-L121 

Suffice to say there is a little bit of impedance mismatch between Nested Diagnostics Contexts and serilogs `PushProperties`

**Comment by damianh** [comment]
Closing as assuming answer is fine.
