### ISSUE TITLE
not repeating class name

### ISSUE THREAD

**Issue by tofutim** [damianh/LibLog#116]
Is there a way to do this without repeating the class name? like maybe using typeof?

```
public class BingSpeechSynth : BaseSpeechSynth
{
    private readonly static ILog log = LogProvider.For<BingSpeechSynth>();
```

**Comment by bartelink** [comment]
You could do `using T = BingSpeechSynth;` and then use the `T` if you want to make it copy-paste safe.

In a `static` initialization context, the `Type` is difficult to obtain in a more DRY (or efficient) manner.

If you were making it an instance field, `GetType()` would not entail repeating the class name, however, that's prone to issues where the actual concrete type is a derived one.

Of course, [there are performance considerations here too](http://csharpindepth.com/Articles/General/Beforefieldinit.aspx), but you're unlikely to find a more straightforward and brief snippet (except for removing the `private`).

I hope someone comes up with an idea and proves me wrong :( 

There are of course reflection tricks, but that's just a bad idea for lots of reasons.

**Comment by damianh** [comment]
_I've been lazy of liblog maintenance, pending netstandard/core settling_

If using typeof you'd have
 `private readonly static ILog log = LogProvider.GetLogger(typeof(BingSpeechSynth));`

Not much of a saving. 

Logger names can be whatever you want them to be; many people don't use the class name.

Closing as there isn't really anything that can be done here.
