### ISSUE TITLE
namespace Logging.Logging when adding LibLog nuget package

### ISSUE THREAD

**Issue by BruceHunter** [damianh/LibLog#118]
Normally, I create a separate project or logging namespace to hold Logging for LibLog.

If you have Blah.Logging.dll -> namespace Blah.Logging

Then you add nuget package LibLog to that DLL / namespace you end up with 

Blah.Logging.Logging in a few places inside the LibLog.cs

Is there a way we can maybe correct this in the future. Maybe detect the current namespace having "Logging" already, so we don't end up with "Logging.Logging" for a namespace.

Thanks

**Comment by bartelink** [comment]
NuGet's expansion/substitution of tokens doesn't have support for such things, and it's not a good road to go down as packages doing tricks like this is not A Good Thing.

The easiest workaround if you do want to split into a separate `.Logging` dll is to use `Blah` as the default namespace for the `Blah.Logging` project / output name, which will have things line up.

The other point to be made is that most people don't end up justifying to themselves the need to separate things out into a project - it's a case of Doctor It Hurts.

**Comment by damianh** [comment]
Thanks for the response there @bartelink :)

> If you have Blah.Logging.dll -> namespace Blah.Logging

Your default namespace doesn't have to be the same name as the dll. Set the default namespace to `Blah` for the Blah.Logging project

I do this sort of thing regularly.
