### ISSUE TITLE
When using with Serilog, not able to format messages to output objects using the @ operator

### ISSUE THREAD

**Issue by ChrisHimsworth** [damianh/LibLog#12]
Would it be possible to change this so when you pass in a list of object params, it is down to each logging provider to decide how to format the message and parameters/args? 
For example, most would use string.Format(CultureInfo.InvariantCulture, message, args)) before writing the message, but for Serilog, you could pass the message and args and it would correctly format the message.

**Comment by damianh** [comment]
I think I have this fixed, [test here](https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests/LogProviders/SerilogLogProviderLoggingTests.cs#L148-L156). Please review :)

Managed to keep the ILog interface to a single method https://github.com/damianh/LibLog/blob/master/src/LibLog/LibLog.cs#L55
