### ISSUE TITLE
Classes of LibLog should have the [ExcludeFromCodeCoverageAttribute]

### ISSUE THREAD

**Issue by mabead** [damianh/LibLog#121]
I have a small project that uses LibLog. When I run my tests with OpenCover to see my coverage, I see that my coverage is quite low. My coverage holes are mainly in LibLog.cs. I obviously don't want that since LibLog.cs is not my code.

Lots of people already use the [ExcludeFromCodeCoverageAttribute](https://msdn.microsoft.com/en-us/library/system.diagnostics.codeanalysis.excludefromcodecoverageattribute(v=vs.110).aspx) to flag code that should not be included in code coverage. I think that the LibLog code should use this attribute to make it easy for everyone to get rid of coverage holes in LibLog.cs.

For sure people could put an exclusion on LibLog.cs. But since most people already exclude coverage for code that have the ExcludeFromCodeCoverageAttribute, it would be simpler for them if LibLog used this attribute.

**Comment by damianh** [comment]
Sure. Please send a PR?

**Comment by mabead** [comment]
PR is here: https://github.com/damianh/LibLog/pull/122

**Comment by damianh** [comment]
Going to tweak this a bit as I need the code coverage when I am developing LibLog... I've made this opt-in via compiler directive `LIBLOG_EXCLUDE_CODE_COVERAGE`. Change is here https://github.com/damianh/LibLog/commit/141510c7cfcb6c0f0f69bd8b7c18799692eb63d9
