### ISSUE TITLE
Multiple independent libraries

### ISSUE THREAD

**Issue by phatcher** [damianh/LibLog#123]
Question really, I have a bunch of projects e.g. Meerkat.Caching, Meerkat.Security, Meerkat.Security.Hmac which are separate NuGet packages but they interact e.g. Meerkat.Security uses Meerkat.Caching

I was using Common.Logging but LibLog looks like a better idea, my problem is that if I put LibLog into each assembly they clash against each other as they all define Meerkat.Logging - most of my projects have Meerkat as a root namespace as assembly boundaries are typically not namespace boundaries.

Any suggestions apart from introducing Meerkat.Logging as its own package, which sounds like a bad idea

**Comment by damianh** [comment]
My advices is, since you own all the Meerkat.* dependees, to go for Meerkat.Logging. Putting LibLog in each one would be over kill, especially if you wanted wire up adapters manually at some stage.
