### ISSUE TITLE
netstandard11?

### ISSUE THREAD

**Issue by tofutim** [damianh/LibLog#124]
Hi I tried installing LibLog into a netstandard11 library today and it seems that the Logging code is not copied in. I do not see an App_Packages folder or the .cs file. ILog and LogProvider not available. :(

![image](https://cloud.githubusercontent.com/assets/157766/21663453/2ef0a14e-d295-11e6-99ef-58685b23d21f.png)

**Update.** Maybe related to DNX issues discussed in https://github.com/damianh/LibLog/issues/35

**Update2.** Maybe this is helpful:
http://blog.nuget.org/20160126/nuget-contentFiles-demystified.html

**Update3.** Or this
http://stackoverflow.com/questions/35985232/nuget-3-3-contentfiles-not-added-to-project

I tried it the following
```
		<contentFiles>
			<files include="cs\any\LibLog.cs.pp" buildAction="Compile" />
		</contentFiles>
    </metadata>
    <files>
        <file src="LibLog.cs.pp" target="contentFiles\cs\any\" />
    </files>
```
but it did not work. Also this did not work
```
		<contentFiles>
			<files include="cs\**\*.*" buildAction="Compile" />
		</contentFiles>
    </metadata>
    <files>
        <file src="LibLog.cs.pp" target="contentFiles\cs\any" />
    </files>
```
nothing gets copied to net46, netstd or pcl.

**Comment by tofutim** [comment]
Great scotts, this works for netstandard11:
```
		<contentFiles>
			<files include="contentFiles\cs\**\*.*" buildAction="Compile" />
		</contentFiles>
    </metadata>
    <files>
        <file src="LibLog.cs.pp" target="contentFiles\cs\any" />
        <file src="LibLog.cs.pp" target="contentFiles\cs\netstandard1.1" />
    </files>
```

Doesn't work for net46 or PCL, but maybe this with the old method will work just fine.

**Comment by damianh** [comment]
Hi, as I mentioned in the PR, I'm not going to do the netstandard work until tooks have settled down. I know that the csproj format has changed again in the upcoming RC release.

For now, copying the class file into your netstandard project and using the `LIBLOG_PORTABLE` directive will work, pending a future release of liblog.

Btw, I want it too for netstandard, so we'll get this done :)

**Comment by damianh** [comment]
Discussion for this is continuing over at #125
