### ISSUE TITLE
Log4Net doesn't work with in .net core (netstandard) project

### ISSUE THREAD

**Issue by MikeGoldsmith** [damianh/LibLog#126]
Hello all

I'm evaluating using LibLog on my library and I've been trying to get LibLog working with some of the different providers under a .net core (netstandard1.3) project and found that Log4Net doesn't work. This is because it tries to bind to Log4Net's `LogManager.GetLogger(string name)` which is not available in netstand1.3 - [code](https://github.com/apache/log4net/blob/4d1e9c10dc6335d472beb7612698cde39b4bccdf/src/LogManager.cs#L125).

When trying to use `Log4NetLogProvder.GetLogger` an invalid Expression is built [here](https://github.com/damianh/LibLog/blob/master/src/LibLog/LibLog.cs#L1247). I think using Log4Net's `GetLogger(Assembly assembly, string name)` would work, but would need to bind the extra assembly parameter. As LibLog is design to be installed directly in the library something like `typeof(ILog).GetTypeInfo().Assembly` should get the correct assembly, but I'm unsure how to build the expression.

I can report NLog's [prerelease](https://www.nuget.org/packages/NLog/5.0.0-beta04) netstandard library does work with LibLog.

**Comment by damianh** [comment]
Hi, sorry, not going to do netstandard related work until tooling has settled. https://github.com/damianh/LibLog/issues/124#issuecomment-274942233

**Comment by damianh** [comment]
(Thanks for the report though!)

**Comment by tofutim** [comment]
I just ran into this with Xamarin.Mac - https://github.com/damianh/LibLog/issues/128 - which for whatever reason gets classified as netstandard13.

**Comment by tofutim** [comment]
just thought of something, if not using PUBLIC, each ILog will be in a different Assembly, so this will not work. I will rethink the PR.

**Comment by phatcher** [comment]
Did you get anywhere with this?

**Comment by MikeGoldsmith** [comment]
No, Damian has indicated he is not willing to invest time into .NET core support for now.

**Comment by damianh** [comment]
I'm blocked by this https://github.com/dotnet/sdk/issues/1100 for packaging reasons.

Fwiw, I'm using LibLog in projects that target NetStandard by [copying the file](https://github.com/SQLStreamStore/SQLStreamStore/tree/master/src/SqlStreamStore/App_Packages/LibLog.4.2) and setting the [compilation constant](https://github.com/SQLStreamStore/SQLStreamStore/blob/master/src/common.props#L14).

**Comment by tofutim** [comment]
We also gave up and copied the file.

**Comment by damianh** [comment]
It appears the blocking issue, https://github.com/dotnet/sdk/issues/1100 , is now moved to Milestone 2.2.0 😞

**Comment by damianh** [comment]
Closing as PR #133 addresses this work. (Pending the SDK issue of course).
