### ISSUE TITLE
LibLog does not detect ILMerged logging libraries

### ISSUE THREAD

**Issue by AndreiMarukovich** [damianh/LibLog#127]
When the logging library, like Serilog or Log4Net, is ILMerged in executable, LibLog is not able to use it because it tries to get types using assembly name. Potential solution is to introduce a fallback for the type resolution like

```
private static Type GetLogManagerType()
{
    return Type.GetType("log4net.LogManager, log4net") ?? Type.GetType("log4net.LogManager");
}

```

If you are okay with this solution, I can submit a PR.

**Comment by damianh** [comment]
ILMerging is for libraries. Don't use it for executables. Use [Fody Costura](https://github.com/Fody/Costura) instead. It's safer too (which solves this problem).
