### ISSUE TITLE
Static Logger and SetCurrentLogProvider() in UnitTests

### ISSUE THREAD

**Issue by michaelschnyder** [damianh/LibLog#130]
Hi

I'm having some issues with the current situation and LibLog 4.2, .NET 4.6.1, MSTest and the VSRunner, NCrunchRunner & Reshaprer Runner. 

I'm using the `SetCurrentLogProvider()` method to use to set my own Logger which captures all log-calls for later assertion. This happens in different tests which may run in any particular order, parallel or not.

#### My DummyLibrary
```c#
public class MyLibrary
{
    static readonly ILog StaticLogger = LogProvider.For<MyLibrary>();
    readonly ILog instanceLogger = LogProvider.For<MyLibrary>();

    public MyLibrary(bool useInstanceLogger = false, bool useStaticLogger = false)
    {
        if (useInstanceLogger) instanceLogger.Info("New Library has been constructed");
        if (useStaticLogger) StaticLogger.Info("New Library has been constructed");
    }
}
```

#### CaptureLogProvider
```c#
public class CaptureLogProvider : ILogProvider
{
    public List<string> StoredLogs { get; } = new List<string>();
    public Logger GetLogger(string name) => this.WriteCore;

    private bool WriteCore(LogLevel loglevel, Func<string> messagefunc, Exception ex, object[] fparams)
    {
        if (messagefunc != null)
            this.StoredLogs.Add(messagefunc());
        return true;
    }
    public IDisposable OpenNestedContext(string message) => null;
    public IDisposable OpenMappedContext(string key, string value) => null;
}
```

I figured out that when starting 2 tests a the same time (any runner), one of the two tests did not capture anything, while as the first test also only captured 1 entry. Please see basic test below, the second one is just a copy.

#### Tests
``` c#
[TestMethod]
public void LogProviderInstance_StaticLogger_Test1()
{
    var p = new CaptureLogProvider();
    LogProvider.SetCurrentLogProvider(p);

    var lib = new MyLibrary(useStaticLogger: true);

    Assert.IsTrue(p.StoredLogs.Any());
    Assert.AreEqual(1, p.StoredLogs.Count);
}

[TestMethod]
public void LogProviderInstance_StaticLogger_Test2()
{
    /* Copy of first test */
}
```

Running these two tests at the same time does fail for the second one, while the first one also only captures 1 single log entry. As you see I created a new instance of the LogProvider for every test but the Logger in `MyFramework` itself is static. I experimented a bit with static/instance and added a couple of unit tests which gave me the following results

| Test | LogProvider | Logger | Result |
|:-----| ------------- | -------- | ---------- |
| LogProviderInstance_StaticLogger | Instance | Static | Fail |
| LogProviderInstance_InstanceLogger | Instance | Instance | Passed |
| StaticLogProvider_StaticLogger_Test | Static | Static | Fail |
| StaticLogProvider_InstanceLogger_Test | Static | Instance | Passed |

It looks like the SetCurrentLogProvider() only works reliable (or can be called multiple times) if the Logger gets created for each instance of `MyFramework`. That makes somehow sense by since the `static` keywork in the Framework-Class. But when following this explanation the number of logs should by 2 and not zero.

### Summary
I'm raising this here, but I don't know if this is really an issue or my approach is just wrong and I should go in the direction as it is explained here: http://dhickey.ie/2015/06/capturing-log-output-in-tests-with-xunit2/ (as far as I understand that does not explain why there are zero entries in the static test)

The complete source-code is available here: https://gist.github.com/michaelschnyder/7475beeaaf223bc0dd3c82acc897bd2e

**Comment by michaelschnyder** [comment]
A little update here: the call to `LogProvider.SetCurrentLogProvider` does not replace the instance in the wrapper or forces LibLog to aquire a new logger by using the newly set LogProvider.

For my case where I had to assert specific Log-Calls, I'm using NestedContexts (`LogProvider.OpenNestedContext(`) and store the log-messages in relation to the contexts.

But am still not sure if the behavior of SetCurrentLogProvider() is valid.

**Comment by michaelschnyder** [comment]
This one is related to the behavior: http://stackoverflow.com/questions/39272937/liblog-asserting-calls-to-the-logger

I'm now using a ConsoleLog Capturing mechanism, but that does not work with any version above 3.1 because LibLog does not write to Console anymore if no LogProvider is registered. See example here: https://github.com/jobbrIO/jobbr-server/blob/develop/source/Jobbr.Tests/Integration/Startup/ConfigurationTests.cs#L210

The issue somehow still exists if I would upgrade to > 3.1 but i would just need to set a CaptureProvider before *any* of the tests start.

**Comment by pnstickne** [comment]
@michaelschnyder For tests, I explicitly re-create the static Logger instance _after_ setting the current Log Provider. This is a bit wonky, although it addresses the issues above.
