### ISSUE TITLE
Extension methods (WarnFormat, WarnException, etc.) can cause Logger to be called with "null" for a message func.

### ISSUE THREAD

**Issue by pnstickne** [damianh/LibLog#131]
Every log extension method (to a non-disabled logger) that first does a check results in at least one "null" entry being supplied to the underlying Logger delegate. This is in addition to any real call with an actual message to log. (master @ 437197286dbb280a84e59aaee22130abd7c36044)

For example, extension method calls IsWarnEnabled which is the crux of this unexpected side-effect.

```
        public static void WarnFormat(this ILog logger, string message, params object[] args)
        {
            if (logger.IsWarnEnabled())
            {
                logger.LogFormat(LogLevel.Warn, message, args);
            }
        }
```

IsWarnEnabled calls LoggerExecutionWrapper.Log (ILog.Log) with a null message

```
        public static bool IsWarnEnabled(this ILog logger)
        {
            GuardAgainstNullLogger(logger);
            return logger.Log(LogLevel.Warn, null);
        }
```

And Log calls the Logger delegate with null when not disabled.

```
        [SuppressMessage("Microsoft.Design", "CA1031:DoNotCatchGeneralExceptionTypes")]
        public bool Log(LogLevel logLevel, Func<string> messageFunc, Exception exception = null, params object[] formatParameters)
        {
            if (_getIsDisabled())
            {
                return false;
            }
            if (messageFunc == null)
            {
                return _logger(logLevel, null);
            }
```

My expectation: ILog.Log is only called once per any logging call, regardless of it comes from an extension method.

**Comment by damianh** [comment]
Hmm yeah agreed that this is unexpected. It's a side effect of fitting everything into the one signature. I'll consider expanding the signature for next version to to separate the logging from checking if it's enabled. _I really don't want to expand the signature beyond that_.

I would argue, however, that one should to mock `ILog` and just use in memory concrete implementations. I use serilog in my tests and I pretty much never assert on whether something is logged or not.

I'll leave this open pending the updated signature which I'll line up for NetStandard2.0

**Comment by damianh** [comment]
Documented guidance [here](https://github.com/damianh/LibLog/wiki/Testing-Guidance). Basically don't mock ILog, use an in-memory sink instead as previously mentioned.

Am considering changing the signature (via separate issue) still however the guidance would remain the same.
