### ISSUE TITLE
templated objects

### ISSUE THREAD

**Issue by tofutim** [damianh/LibLog#135]
In the following code

```
	public abstract class ZumoTableController<TData> : TableController<TData> where TData : class, ITableData
	{
		private static readonly ILog _logger = LogProvider.For<ZumoTableController<TData>>();

		protected ZumoUser zumoUser;

		protected override void Initialize(HttpControllerContext controllerContext)
		{
			base.Initialize(controllerContext);
			zumoUser = User.CreateZumoUser(Request);
			_logger.DebugFormat("{0} requested {1}", zumoUser, controllerContext.Request.RequestUri.PathAndQuery);
		}
	}
```

LibLog (or maybe log4net?) appears to not like the templated data. I end up with the class in the debug message looking like "0, Culture=neutral, PublicKeyToken=null]] "

```
06:03:11.261 [12] DEBUG 0, Culture=neutral, PublicKeyToken=null]] - Tim requested /tables/todoitem 
06:03:05.630 [10] DEBUG ZumoUserIdProvider - Tim requested /signalr/start?transport=webSockets&clientProtocol=1.5&connectionToken=7sy%2B1mcgcKAPfQ1kQ4TusSYcdwjrGjI09EIR6hK%2BbU%2FY8Ig%2F7K35jNaycaCrLg2xwE9CfAXyUO9E5gS%2BrYPjvo0FOIIX%2FNBNcWi5v4rcRA3zsci1eVRH3ZgaY4gN7ex1&connectionData=%5B%7B%22name%22%3A%22monitor%22%7D%5D&_=1490119367001
```
I'll try to increase the length, looks like it is getting truncated. But was hoping to see `ZumoTableController<ToDoItem>`

Here is what actually is in the loggingEvent
`kamelos.Controllers.ZumoTableController`1[[kamelos.DataObjects.TodoItem, kamelos, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]]`

![image](https://cloud.githubusercontent.com/assets/157766/24163298/5cd02eb8-0e27-11e7-9c47-b7c4c62649ed.png)

**Comment by damianh** [comment]
Closing due to age. Please comment if it is still an issue with v5.0.0. Thanks.
