### ISSUE TITLE
Possibly update instructions for new csproj

### ISSUE THREAD

**Issue by pardahlman** [damianh/LibLog#137]
I'm using the new `.csproj` project for a small library. I'm targeting .NET Framework 4.5.1 as well as NETStandard 1.5. It turned out that in order to compile against `net451` I had to include a conditional `ItemGroup` and reference `Microsoft.Csharp`:

```xml
<ItemGroup Condition=" '$(TargetFramework)' == 'net451' ">
  <Reference Include="Microsoft.CSharp" />
</ItemGroup>
```

Perhaps I'm one of few still targeting .NET Framework, I just thought you might want to have this tidbit somewhere in your documentation. It was tricky to find the issue, as the compiler indicated that it was a problem with the `netstandard1.5` build.

Thanks a a bunch for this framework 👍

**Comment by damianh** [comment]
Yeah that's because of the dynamic. Updated the readme. Thanks for the report ;)
