### ISSUE TITLE
Support for diagnostic contexts

### ISSUE THREAD

**Issue by DannyRyman** [damianh/LibLog#14]
Currently we make use of context to set correlation identifiers for all our log requests.  Currently this is not supported using LibLog.  Do you think this would be a good extension to LibLog?

http://logging.apache.org/log4net/release/manual/contexts.html

http://nblumhardt.com/2013/09/serilog-gets-a-diagnostic-context/

http://nlog-project.org/documentation/v2.0.1/html/T_NLog_MappedDiagnosticsContext.htm

**Comment by damianh** [comment]
Implemented in #27
