### ISSUE TITLE
Replace Gibraltar.Agent with Loupe.Agent.Core

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#148]
@kendallmiller will there be a `netstandard` version of Gibraltar.Agent?

For now I'm going to exclude the code and the tests.

**Comment by kendallmiller** [comment]
We published a NetStandard 2 version of the agent a months ago, it's [on NuGet](https://www.nuget.org/packages/Loupe.Agent.Core/) and is [now open source](https://github.com/GibraltarSoftware/Loupe.Agent.Core) as well.

This port of the Loupe Agent doesn't have unit test support yet - that's coming in our next big update but I'll try to slide it into this one so we can close that longstanding testing issue.

**Comment by damianh** [comment]
Ah, will use that. Cheers!
