### ISSUE TITLE
VB.NET projects support

### ISSUE THREAD

**Issue by filippobottega** [damianh/LibLog#153]
Hello,
  is it possible to use LibLog in a vbproj NetStandard 2.0 Library?
  If not, how can I adapt the liblog.cs file to be used in a VB project?

  Thank you,
    Filippo.

**Comment by damianh** [comment]
Hi, 

LibLog is written in C# and included in your project as code. Obviously it won't compile in a vb.net project and I have no intention of creating a VB port. It's MIT licence, do if someone wants to do a VB port they are free to do co.

Cheers
