### ISSUE TITLE
#define LIBLOG_PROVIDERS_ONLY throws error 'LoggerExecutionWrapper not found'

### ISSUE THREAD

**Issue by ahmadqarshi** [damianh/LibLog#155]
I am already using Nlog in my application. For logging functionality from Quartz.net library I added latest LibLog library into my application. 

After adding `#define LIBLOG_PROVIDERS_ONLY`, I am getting an error that `LoggerExecutionWrapper`  and `LogExtensions` are not found.

**Comment by hcoona** [comment]
I'm also facing this issue.

**Comment by damianh** [comment]
Him

LibLog is means for libraries. You are not meant to add it to applications. If Quartz.net already uses LibLog internally (I don't know if it does), it should just work with NLog. You may need to set up appropriate sinks / filters etc.

Regading `#define LIBLOG_PROVIDERS_ONLY` am going to remove that feature. It is causing too much complexity.
