### ISSUE TITLE
.net Standard Support

### ISSUE THREAD

**Issue by mit-jamie-clayton** [damianh/LibLog#156]
If I run the Microsoft Portability Analyzer (https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer) over liblog I get a number of blocking warnings around various .net api's that are not compatible with the .net Standard.

> System.Diagnostics.StackTrace : Currently there is no workaround, but we are working on it. Please   check back
> System.Diagnostics.StackFrame: Consider removing   dependency on this API.

Is there any plans to address this limitation with the current codebase?

**Comment by damianh** [comment]
Fixed in #149
