### ISSUE TITLE
not working with PackageReference

### ISSUE THREAD

**Issue by rychlym** [damianh/LibLog#157]
Hello, 
it behaves differently on adding nuget refference to this lib. when a project uses the PackageReference (instead using packages.config).
It seems not doing anything.

**Comment by phatcher** [comment]
PackageReference doesn't copy content so this won't work - you are better copying the current source from the git repository and manually changing the namespace etc

**Comment by damianh** [comment]
Yeah the readme mentioned that you had to copy-paste because content files in .net core sdk were broken. Fixed on master with #149 with v5.0.0 available shortly.
