### ISSUE TITLE
Version 5.0.0 on nuget.org

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#164]
https://github.com/damianh/LibLog/releases/tag/v5.0.0

That took longer time than I hoped. I feel the same problems with Common.Logging exist in Microsoft.Extensions.Logging(.Abstractions). Of which they appear to be doing releases in lockstep with other package versions in the ecosystem as opposed to versioning it in it's one right. That is, diamond dependencies remain for library authors and especially for library that are not coupled to the AspNetCore world.

I'd prefer if .NET has some sort of structural typing where library authors can adopt one or more community contracts. [Shapes](https://github.com/dotnet/csharplang/issues/164) are off the horizon so we're going to be stuck with diamond dependencies for some time. 

I've been using this for > 7 years now and can see there is a few more left to go.

Cheers.

**Comment by snakefoot** [comment]
@damianh Any reason why the nuget-package is suddenly split into multiple files, instead of just LibLog.cs as before?

And why this folder-structure (new):

![image](https://user-images.githubusercontent.com/11509660/40789417-a8b905ca-64f2-11e8-90d4-8f8b38be694d.png)


Compared to before (old):

![image](https://user-images.githubusercontent.com/11509660/40789444-b7766fa8-64f2-11e8-8464-cb91f98560fa.png)

**Comment by snakefoot** [comment]
Tried testing it on a Net45-library and nothing happened when adding the nuget-package.

**Comment by snakefoot** [comment]
Tried to add the special attribute to allow NetStandard dependencies, but still not working:

`<RestoreProjectStyle>PackageReference</RestoreProjectStyle>`

**Comment by damianh** [comment]
@snakefoot As mentioned in the release notes, version 5.0.0 is for netstandard2.0 or later and for new sdk project format only. The previous 4.x versions are for the old csproj formats and older runtimes.

In netstandard projects the files are not copied directly into into the project itself (vs visible in `App_Packages/LibLog`). The single file approach was to reduce the noise in peoples' projects. Since it's no longer visible the multi-file is just easier to reason and maintain.

I can consider patching 4.x with some fixes that went into v5.0.0. I can also consider supporting a lower netstandard version but the 1.xs have low adoption.

**Comment by damianh** [comment]
> No longer true: Just copy the Liblog.cs and it works

I need to update the docs. If people still need to copy the single (would like to know reasons), can consider reverting.
