### ISSUE TITLE
Restore support for .NET Framework 4.5.2

### ISSUE THREAD

**Issue by pomma89** [damianh/LibLog#167]
Hi @damianh,

Could you restore support for "classic" .NET Framework, at least version 4.5.2? Your library is very useful and I would need it on libraries multi-targeting both .NET (>= 4.5.2) and .NET Core.

I quickly tried to enable multi-targeting on your library and it seems to be compiling. If you are willing to restore support, then I might send you a PR.

Thanks!

**Comment by damianh** [comment]
Ok I will consider it if it not too much ifdefs etc. Technically 4.5.2 is still "supported". I'm only going to support SDK csproj formats going forward though.

**Comment by damianh** [comment]
Work around for now is to use the 4.x versions.

**Comment by damianh** [comment]
#168 Merged. Thanks! :)

**Comment by damianh** [comment]
`v5.0.1` is on nuget.org.

**Comment by pomma89** [comment]
Thank you!
