### ISSUE TITLE
Make all types internal

### ISSUE THREAD

**Issue by samcragg** [damianh/LibLog#169]
First of all, thanks for the library; it's great to be able to not force users of my library to depend on a logging framework!

Just installed the latest 5.0.0 and I defined `LIBLOG_PROVIDERS_ONLY` to make everything internal (so as not to leak the logging outside of my library), however, `LibLogException` remains public.

Any chance this could be make internal as well if `LIBLOG_PROVIDERS_ONLY` is defined?

Thanks

**Comment by samcragg** [comment]
You can throw that exception, even if it's internal, though only the user of the library would be able to catch them (without the generic `catch (Exception ex)`) - if you wanted the end user of the library to be able to catch them then I guess you could make `LibLogException` inherit from [InvalidOperationException](https://docs.microsoft.com/en-gb/dotnet/api/system.invalidoperationexception), which should fit the bill as the docs state it's:

> used in cases when the failure to invoke a method is caused by reasons other than invalid arguments

**Comment by damianh** [comment]
As this is a breaking change, I'll reserve it for version 6. However, I feel this is low priority (unless I can be convinced otherwise!). This also explains why my response is so late... At this time, my priorities are predominately around bugs. Thx.

**Comment by mniak** [comment]
Do you accept contributions?

**Comment by mniak** [comment]
Anyways, I've made a PR for this.  #231
