### ISSUE TITLE
LibLog 5.x files don't have <auto-generated/> tag to skip analyzers

### ISSUE THREAD

**Issue by qdot** [damianh/LibLog#174]
Trying to use LibLog 5.x through nuget. The files generated from the .pp files don't include

```
// <auto-generated/>
```

So they're picked up by analyzers (StyleCop) in this case and cause the project to fail analysis/build.

I think this is just a matter of adding that comment to the beginning of the *.pp files, I can make a PR for that if you'd like, just want to make sure I'm correct and not missing some other solution.

**Comment by damianh** [comment]
Is this still the case for .netstandard2.0 projects? Is stylecop analysing cs files in the `obj` folder too?

**Comment by qdot** [comment]
Yeah, I was getting these errors on a .netstandard2.0 project. Does seem a bit weird that it's analyzing obj, but I think StyleCop may just try to look for *.cs under the project directory.

**Comment by damianh** [comment]
Ok, will take a PR for this :)

**Comment by qdot** [comment]
Thanks for getting this done! I've been traveling and didn't have time to PR. :slightly_smiling_face:
