### ISSUE TITLE
Is it still possible to "just copy LibLog.cs"?

### ISSUE THREAD

**Issue by flytzen** [damianh/LibLog#178]
The [Wiki](https://github.com/damianh/LibLog/wiki/Using) still refers to the ability to "just copy `Liblog.cs` but the Wiki actually refers to `LogProvider.cs.pp` - and, in any case, I don't think there is a single file you can just copy in, in v5 any more?

I am assuming this is by design and only the nuget approach is supported now. If this is the case, I'm happy to edit the wiki.

**Comment by damianh** [comment]
Hi, no. Sorry docs out of date. I'll fix. Thx.

**Comment by damianh** [comment]
Done.
