### ISSUE TITLE
The "Extending" Wiki page contains outdated information

### ISSUE THREAD

**Issue by ShukiParty** [damianh/LibLog#182]
Hi,
The "Extending" Wiki page contains outdated information.

According to the The "Extending" Wiki page. see: https://github.com/damianh/LibLog/wiki/Extending
Need to implement ILogger and ILoggerFactory, but I can't see these interfaces in the LibLog source code.

Thanks

**Comment by ShukiParty** [comment]
> Hi,
> The "Extending" Wiki page contains outdated information.
> 
> I am using EasyNetQ in my project that use LibLog for logging support.
> Additionally, I have a custom logging library (not log4net/nlog/serilog or other well known logging library).
> I want EasyNetQ log messages to be written using my own logging library, to the same log file that is already used throughout the application.
> 
> According to the The "Extending" Wiki page. see: https://github.com/damianh/LibLog/wiki/Extending
> I need to implement ILogger and ILoggerFactory, but I can't see these interfaces in the LibLog source code.
> 
> Also, I tried implementing ILogProvider, but I am not sure how OpenNestedContext and OpenMappedContext should be implemented..
> Returning null or Dummy IDisposable class that do nothing causes errors and unwanted behaviour.
> 
> Thanks

**Comment by doublnt** [comment]
@ShukiParty The interface may be is Microsoft.Extensions.Logging interface https://github.com/aspnet/Extensions/tree/master/src/Logging/Logging.Abstractions/src

**Comment by damianh** [comment]
Closing because of age and #270
