### ISSUE TITLE
Does LibLog only work for 'netstandard2.0' and 'net452'?

### ISSUE THREAD

**Issue by ErnestoGarciaGenesys** [damianh/LibLog#183]
I tried with 'net45', but LibLog code files weren't included in the build.

**Comment by ErnestoGarciaGenesys** [comment]
I have checked, and it supports 'netstandard2.0' and 'net452' and higher, so its dependencies are well declared.

**Comment by damianh** [comment]
Yes. Specifically one must use the new sdk csproj format. The old csproj format is no longer supported.

**Comment by aateeque** [comment]
I have:
`<TargetFrameworks>netstandard2.0;net451</TargetFrameworks>`

But I get:

```c#
1>      KdbQueryConnection.cs(6,17,6,24): error CS0234: The type or namespace name 'Logging' does not exist in the namespace 'KdbClient' (are you missing an assembly reference?)
```

This is how I am referencing LibLog:

```xml
    <PackageReference Include="LibLog" Version="5.0.2">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
```

And directly reference:

```
<PackageReference Include="Microsoft.CSharp" Version="4.4.0" />
```
