### ISSUE TITLE
Release v 5.0.3

### ISSUE THREAD

**Issue by flytzen** [damianh/LibLog#184]
Sorry to hassle, but would you be able to release 5.0.3 to Nuget?
It would really help me out.

Thanks

PS If you are interested, I'd be happy to help set up an Azure devops pipeline to do it. I just [did some work on some of mine](https://www.lytzen.name/2018/10/03/publish-nuget-packages-with-azure-devops.html) so can drop it in quite easily. I'd just need to talk to you about Nuget keys etc.

**Comment by dmelinosky** [comment]
Seconded

**Comment by damianh** [comment]
On [nuget.org](https://www.nuget.org/packages/LibLog/5.0.3). Thanks for your patience.

@flytzen thanks for sharing that blog post. Very interesting, will study!

**Comment by damianh** [comment]
You are welcome :)
