### ISSUE TITLE
Package files are being checked by stylecop

### ISSUE THREAD

**Issue by ArchB1aZe** [damianh/LibLog#186]
Hey,

We are using your package in our project but the problem is our stylecop analyzer is checkiing the files generated by this package for errors. Only way to skip the files is if we add // <auto-generated> tag on top of each file which is a temporary fix. Is it possible for you to add that tag on top of your files so things stay the same even if there is an update or something? Because right now in the 5.x version there are multiple files being generated so we have to manually add the tag in every file in every project which is a tedious task.

**Comment by damianh** [comment]
Acutally there was a PR that addesses this already #177 . Going to ship an patch release soon.
