### ISSUE TITLE
check for null in LogExtensions

### ISSUE THREAD

**Issue by oleksabor** [damianh/LibLog#192]
Hi
I'm using LibLog to avoid logging library dependency building small packages
However I would like not to push users to implement `ILog` interface when my packages are used. That is why I have to check and disable logging if it was not initialized.

It is possible to write some helper methods or use Action<ILog> with null check before. But it makes my code not very clean
I'd like to ask may be it makes sense to modify source LibLog package with null check and disable logging if it is null? To make `LogExtension` methods to log only if logger is not null

Like below

```
public static void Debug(this ILog logger, string message)
 {
        if (logger != null && logger.IsDebugEnabled())
        {
                logger.Log(LogLevel.Debug, message.AsFunc());
        }
}
```

Or to update `Is*Enabled` methods like
```
public static bool IsDebugEnabled(this ILog logger)
{
    return logger != null && logger.Log(LogLevel.Debug, null);
}
```
I can make changes and generate pull request if it is acceptable

How do you use LibLog properties that can be not initialized ? I do not think that guarding each `log.Debug` with `if (log != null)` is a nice idea.

Regards

**Comment by damianh** [comment]
Just catching up on these issue. Let me chew on this one a bit..

**Comment by shatl** [comment]
@oleksabor  Have you considered implementing [Null Object pattern ](https://en.wikipedia.org/wiki/Null_object_pattern) ?

**Comment by AroglDarthu** [comment]
> @oleksabor Have you considered implementing [Null Object pattern ](https://en.wikipedia.org/wiki/Null_object_pattern) ?

My thoughts exactly. No need to change any usages. Just fallback to a `NullLogger`.

**Comment by damianh** [comment]
Seems we have a solution / workaround. Thanks @shatl and @AroglDarthu :)

**Comment by oleksabor** [comment]
@AroglDarthu `NullLogger` rocks thanks a billion
