### ISSUE TITLE
Compiler pre v7 support out of the box

### ISSUE THREAD

**Issue by ericnewton76** [damianh/LibLog#194]
Hi.  Great library.  I was pointed here as a possible solution by the NLog maintainers... so you are getting noticed!

I have a unique situation where I cant upload/reference assemblies in a dotnet based CMS SaaS solution.  I do have the ability to upload source files all day long, however those source files get compiled with the old compilers present in the NetFramework and zero support right now for any of the Microsoft.Net.Compilers way of upgrading the compile time to newer versions.

Because of that... I cant use `=>` **property** shorthand functions, or any of the newer C# features for the time being.

Would you mind if I submit a PR that just downgrades these type of issues?

**Comment by snakefoot** [comment]
Since all newer refactoring tools will encourage one to make use of the latest C#-features, then I don't think you will get a promise that all future PRs will not make use of new syntax sugar. Unless you volunteer to become full time maintainer of LibLog :). 

Btw. there are very few changes to LibLog so maintaining your own custom version should not be a big hazzle.

**Comment by ericnewton76** [comment]
@snakefoot agreed.  And you know basically most of my situation... lol

**Comment by damianh** [comment]
Hi @ericnewton76,

this is a unique request. I am somewhat weary of supporting unique scenarios, especially ones I can't really test. Before I consider targeting a previous version of C# 7, can you verify that the this CMS SaaS thing can build SDK based `.csproj`? LibLog, as of version 5 only supports these project formats. It would be very strange to for these project formats to be supported in the CMS SaaS but C# 7 _not_.

Thx.

**Comment by damianh** [comment]
You should also check if v4.x will work for you too. The major difference between v4 and v5 was the move to supporting the new SDK csproj format.

**Comment by ericnewton76** [comment]
The cms handles compilation itself, I only get to upload cs files. It also has its own aspx parser but that’s a slightly different topic. 

The biggest pain I’ll have is that the cms uses a specific csc version (probably whatever is current framework dir csc and probably still 4.5 I would guess)

It’s entirely possible I’ll have to maintain a separate fork for the time being if you don’t wanna merge. I’m fine with that.

**Comment by damianh** [comment]
Sounds a bit nasty :S . Though... it's possible to set the LangVersion in an SDK project. I'll check the PR and if the overhead / pain of maintaining a down level lang version support is not too much, then I will consider it.

**Comment by damianh** [comment]
Fixed in #199
