### ISSUE TITLE
Nuget v3 not writing content and .pp files to .cs files

### ISSUE THREAD

**Issue by ericnewton76** [damianh/LibLog#195]
Okay, so I added LibLog to a project, but Nuget seems to have not done anything with the .pp files.

Might need to create a script or something to run that transformation step now.  

I cant seem to find any documentation of that change so maybe its my machine?  Im using VS2017 15.9

**Comment by ericnewton76** [comment]
Btw, I just finished up a utility that can dip into the CSPROJ file using the Roslyn and MSBuild workspace providers, not sure what the solution to this particular problem would be since a lot of packages depend on content trasformation

**Comment by damianh** [comment]
I can't repro this. Below is a screen shot of a fresh project that where I installed LibLog. Compiles fine, cs files are in obj and namespaces are correct (though had to add the `Microsoft.CSharp` package reference). Nuget (any version) isn't involved here; it part of an msbuild sdk task now.

![image](https://user-images.githubusercontent.com/57436/50682927-b1cc7b00-1010-11e9-91f2-f5dd61d9831f.png)

Note: LibLog only works with new SDK csproj formats. 

Marking it as `invalid` (aka - `no-repro`). If you can upload an example project to github where it is not working I can take a look. Cheers.
