### ISSUE TITLE
Source packer all into a single file suggestion

### ISSUE THREAD

**Issue by ericnewton76** [damianh/LibLog#196]
btw, I have written a roslyn based source packer... that you might be interested in.  It can take all source files in a CSPROJ and pack them into one file.

It consolidates all usings outside the namespace declarations into one or more targetfiles.

You add comment directives to your files to control the packer...

```c#
//!packer:targetFile=LogProviders.cs
```

Its located here... [post link here]

**Comment by ericnewton76** [comment]
Theoretically you transform the ..pp files to .cs files, then pack all the bits into a single file... bam... you're back to simple "copy this one file" instructions

**Comment by damianh** [comment]
Hi @ericnewton76,

In v4 and prior, it was packaged and available as a single file for the following reasons:

1. In the early days of the project there was no mechanism to install the source code via nuget or other means. Single file here was useful.
2. Then nuget supported `.pp` file transform. It was still included in your actual project source code and committed to version control. One file was preferable over littering many files into other peoples source. 3. Not eveyone could use nuget or could use it's transforms (xamarin / mono), so single file helped.
3. Then the whole vNext -> ASP5 -> DNX -> .NET Core thing happened over a few yers where source code nuget packages and/or transforms not supported. Single file to the rescue...
4. Then, around .NET core 2.0, the source code transforms became supported again in the SDK as a build task. This time cross platform and works in most platforms. It also went directly to the `obj` folder and not inside your repo. The single file is no longer necessary.

So as of version 5, the files are split out for my own maintainability reasons and should be totally hidden from the consumer (though fxcop and others still seem to see it...).

I won't be going back to the single file mechanism. However, for those stuck on old platforms / mechanisms, which you appear to be, they can still use the v4.x line (which I'm willing to patch for a while). 

In the end, as @snakefoot mentioned in another thread, LibLog changes very slowly (it's been surprisingly reliable tbh), so for your unique case, fork and copy is totally a reasonable away to go (it's MIT after all).

Cheers.
