### ISSUE TITLE
can't use with .net framework 4.7.2

### ISSUE THREAD

**Issue by oleksabor** [damianh/LibLog#202]
Hello

Seems that something is wrong with latest 5.0.5 nuget LibLog package. 
I've just created new Windows desktop console application, set it to use .Net Framework 4.7.2 and tried to install latest LibLog package. VS 2017 (version 15.9.5) package manager log is below:
```
Could not install package 'LibLog 5.0.5'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.
```

However I can use LibLog 4.2.6 without any problem in this project.

**Comment by damianh** [comment]
1. Windows Desktop Console applications, when created via visual studio, uses the old project style. As of V5, LibLog only supports the new SDK csproj format. Either convert the csproj to new project format or use LibLog 4.x https://github.com/damianh/LibLog#availability-for-old-csproj-format 
 2. LibLog is for **libraries**. Installing into an application (exe) doesn't make sense.

HTH

**Comment by oleksabor** [comment]
thank you for clarification about project types I've missed it

However I'd like to note that found LibLog very useful in the application (exe) too. I consider it like additional abstraction level
If certain logger is used then it is hard coded into the application source code. Namespaces, log framework manager etc. And then it takes a lot of time to change log engine if it happens. Or if namespace was changed with next log framework version (like it was with MS Unity despite the fact it is not a log framework)
That is why I'm using LibLog in exe. Sorry for inconvenience.

**Comment by damianh** [comment]
No inconvenience at all.

Reasonable use case. Sure if it works for you, carry on.
