### ISSUE TITLE
Debug() vs DebugFormat() vs DebugException()

### ISSUE THREAD

**Issue by shatl** [damianh/LibLog#226]
For every logging level (e.g. Debug) there are methods with following signatures:

Debug(message)
Debug(func<message>)
Debug(message, formatArgs)
Debug(exception, message, formatArgs..)
DebugException(message, exception)
DebugException(message, exception, formatArgs)
DebugFormat(message, formatArgs)

DebugException and DebugFormat seems to be redundant since the same can be achieved using Debug(..) method calls. 

Do we really need them?

**Comment by shatl** [comment]
these are duplicates:

* `Debug(message, formatArgs)` and `DebugFormat(message, formatArgs)` 
* `Debug(exception, message, formatArgs..)` and `DebugException(message, exception, formatArgs)`

**Comment by damianh** [comment]
They appear to be duplicates. However removing them will be a breaking change and a new major version. As I'm deprecating this library (see #270) so I won't be making fixes here.
