### ISSUE TITLE
support for structured logging when using NLog 4.5 or upper

### ISSUE THREAD

**Issue by newbe36524** [damianh/LibLog#239]
something same to #45 
when using [NLog 4.5 or upper](https://github.com/NLog/NLog/wiki/How-to-use-structured-logging) it will be support to use structured logging native.

I will a do some work on this and submit a PR.

**Comment by snakefoot** [comment]
This is already supported in LibLog 5.0.3 (Be careful with using LibLog ver. 5.0.5 or newer until #233 has been merged).

Your PullRequest is targeting LibLog 4-branch.

**Comment by newbe36524** [comment]
@snakefoot  would probably use this version (Coming from #145 + #142) to support this feature :

https://github.com/snakefoot/LibLog/blob/1362d476238d405eba01f11bba28e6a4d858773c/src/LibLog/LibLog.cs (Choose "Raw" for copy-paste)

And just update your own copy of LibLog.cs.
