### ISSUE TITLE
LibLog 4.2.6 does not working on framework 4.7.1

### ISSUE THREAD

**Issue by Dypso** [damianh/LibLog#244]
I have reproduced my bug in a demo application : 
 - a simple console application with framework 4.7.1 and Serilog 2.0.0.0
 - a class library with framework 4.7.1 referencing LibLog 4.2.6 
 - IDE used : VS2017
[ConsoleMain.zip](https://github.com/damianh/LibLog/files/3246576/ConsoleMain.zip)

The main program of the console application call a method from the class library aimed to output some info on the console output. But nothing appear. Tracking down in debug mode show that the current logger does not seem to be enabled....

**Comment by aboldarev** [comment]
It's not a real LibLog Issue. You have to set an shared Serilog logger in order to let a LibLog know about witch Logger should be called 
```
         using (var log = new LoggerConfiguration()

                .MinimumLevel.Verbose()
                .WriteTo.Console()
                .CreateLogger())
            {
               Serilog.Log.Logger = log; <-- set Serilog shared logger 
                log.Information("Hello, Serilog!");
             ....
```

**Comment by damianh** [comment]
Thanks for assistance @aboldarev
