### ISSUE TITLE
Info for Wiki? Solution with many projects, internal and InternalsVisibleTo

### ISSUE THREAD

**Issue by holytshirt** [damianh/LibLog#245]
This is just more information for your wiki.

If you have a solution with many projects and have a "core" project with LibLog and you are following the recommended advice and using InternalsVisibleTo to share LibLog
```csharp
[assembly: InternalsVisibleTo("Core.Blah.Sender")] 
[assembly: InternalsVisibleTo("Core.Blah.Reciever")
 ```
You will run into issues when your "core" project is signed and most other projects are signed but a few are not signed as their dependencies are not signed. The InternalsVisibleTo only works if all the projects are signed :(

```csharp
[assembly: InternalsVisibleTo("Core.Blah.Sender, PublicKey=...01da89e501169...")]
[assembly: InternalsVisibleTo("Core.Blah.Reciever, PublicKey=...01da89e501169...")] 
 ```
You will get this error when building
```
error CS0281: Friend access was granted by 'Core.Blah, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a90f5645ae233e2c', but the public key of the output assembly ('') does not match that specified by the InternalsVisibleTo attribute in the granting assembly.
````
If you remove the public key 
```csharp
[assembly: InternalsVisibleTo("Core.Blah.Sender, PublicKey=...01da89e501169...")]
[assembly: InternalsVisibleTo("Core.Blah.Reciever")] 
 ```
You get this error 
```
Error CS1726 Friend assembly reference 'Core.Blah.Reciever' is invalid. Strong-name signed assemblies must specify a public key in their InternalsVisibleTo declarations.
```

Hope this helps someone

**Comment by aireq** [comment]
FYI, 

I just created an alternative to LibLog I'm calling [MinLibLog](https://github.com/aireq/MinLibLog) that works well with multiple projects with out having to use `InternalsVisibleTo` attributes.

You define single `Func<string, Action<DateTime, int, string, Exception, object[]>>` delegate instance in your application, which is passed the name of a logger, and returns the Action<> that will handle log messages. You then assign this delegate as the `LogProvider` for as many libraries as you want.

Applications do not need to depend on library specific `ILog` or `LogLevel` types, or any types that aren't in the core .Net `System` namespace.

**Comment by damianh** [comment]
Thanks @holytshirt will add it to wiki.
