### ISSUE TITLE
Method name not outputing correctly in Log4Net logger.

### ISSUE THREAD

**Issue by noel-honksw-com** [damianh/LibLog#25]
When logging using Log4Net when outputting the method name where the logger is used the method name is **CallSite.Target** rather than the actual method name used.

For example using a Log4Net layout like the following results in incorrect behaviour.

```xml
<layout type="log4net.Layout.PatternLayout">
    <!-- &#x9; == TAB character as a seperator between each field.-->
    <param name="ConversionPattern" value="[${COMPUTERNAME}]&#x9;[%date{ISO8601}]&#x9;[%-5level]&#x9;[%thread]&#x9;[%logger]&#x9;[%method]&#x9;[%property{NDC}]&#x9;[%message %exception] &#x9;%newline" />
</layout>
```

This outputs the following, **CallSite.Target** should contain the method name.
```text
[NL-DEV]	[2015-01-22 16:29:20,242]	[DEBUG]	[6]	[zhapi.Bootstrapper]	[CallSite.Target]	[(null)]	[Enabling CORS Support ]
```

**Comment by noel-honksw-com** [comment]
Hi Damian, If you need any further clarification on this just let me know I'd be happy to help out, loving the concept of LibLog by the way.

**Comment by damianh** [comment]
I'm guessing Log4Net is getting the most recent item from the call stack which it is then using it for the method name / location info.  Log4Net is invoked via reflection in LibLog and this is the reason you are seeing `CallSite.Target`. 

Is there any way for LibLog to explicitly set the location information per log write that I could investigate? If not, I'm not sure this is fixable :(

**Comment by noel-honksw-com** [comment]
Hi Damian, the only thing I can think of is using the [CallerMemberNameAttribute](https://msdn.microsoft.com/en-us/library/system.runtime.compilerservices.callermembernameattribute(v=vs.110).aspx) to somehow get this down to Log4Net by setting a custom property in Log4Net, called say *LIbLogMethod* and using it in the Log4Net Pattern like %property{LIbLogMethod}.

**Comment by damianh** [comment]
`CallerMemberNameAttribute` is .net 4.5 only though, I'm specifically supporting .net 4.0.

I'll take a look at setting custom property. 

Cheers.

**Comment by noel-honksw-com** [comment]
If you have the stack frames already then you don't need to use the attribute at all.
Hope it works out Damian if you need a hand let me know, can do testing etc.

Cheers
Noel

-----Original Message-----

**Comment by damianh** [comment]
I've looked at the log4net api and there doesn't seem to be a way for me to easily set the LocationInfo.

From https://logging.apache.org/log4net/release/sdk/log4net.Core.LocationInfo.html :

> This means that in a Release build the caller information may be incomplete or may not exist at all! Therefore caller location information cannot be relied upon in a Release build.

So it isn't reliable at all anyway, even if I went the custom property route...

**Comment by noel-honksw-com** [comment]
Hi Damien, Sorry for taking so long to get back to you, I think something is better than nothing, In all the years I've being using Log4Net I only remember once seeing it unable to get the method name for logging, so even if it's unreliable in Release builds as is stated in the .NET documentation as least it's pretty good.
What do you think?

**Comment by damianh** [comment]
It appears the [same problem exists with Common.Logging](http://sourceforge.net/p/netcommon/bugs/12/) (also [here](http://mail-archives.apache.org/mod_mbox/logging-log4net-user/200701.mbox/%3C20070119235802.62623.qmail@web30513.mail.mud.yahoo.com%3E)) . I can't find anywhere where facade / wrapper is used that solves this :disappointed:

**Comment by damianh** [comment]
Closing this as wontfix ("cant fix" really). There doesn't appear to be anything `LibLog` can do AND it wouldn't be reliable anyway.
