### ISSUE TITLE
log4net.Core.LoggingEvent not all properties filled

### ISSUE THREAD

**Issue by aivarasgg** [damianh/LibLog#252]
I am looking into LibLog as a possible replacement for log4net library that we use in our projects, it would be nice to abstract away the logging library and while I was running the tests of LibLog I noticed that it does not fill log4net.Core.LoggingEvent correctly, quite a few important properties are not filled:
- Domain
- LocationInformation
- UserName

I did not investigate why it is not filled yet, maybe you have an idea.
![LoggingEvent](https://user-images.githubusercontent.com/32884008/61769912-2c61ba00-adec-11e9-9ff4-b9518add2d0c.PNG)

**Comment by aivarasgg** [comment]
I've done some digging and it seems like the problem is on log4net side, currently they do not really support netstandard2.0, plus in the code it says
`// NETSTANDARD1_3 TODO requires platform-specific code. On compact framework there's no notion of current Windows user`.

There is not much going on on log4net repository, last commit on `feature/netstandard-2.0` branch is two years old.

I think this issue can be closed.

**Comment by damianh** [comment]
Thanks for follow up.
