### ISSUE TITLE
.NET Full Framework 4.8 support

### ISSUE THREAD

**Issue by chiefengineer** [damianh/LibLog#254]
Error:" Could not install package 'LibLog 5.0.6'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.8', but the package does not contain any assembly references or content files that are compatible with that framework. 

For more information, contact the package author. "

**Comment by damianh** [comment]
What csproj format are you using?

**Comment by chiefengineer** [comment]
I dislike sounding ignorant, but...there is more than one? How can I find
out?

"Bang the Button - It Just Works!"

**Comment by damianh** [comment]
https://natemcmaster.com/blog/2017/03/09/vs2015-to-vs2017-upgrade/
http://www.albertocorrales.com/2018/12/why-you-should-migrate-your-old-csproj.html
https://www.hanselman.com/blog/UpgradingAnExistingNETProjectFilesToTheLeanNewCSPROJFormatFromNETCore.aspx

LibLog >= 5.0.0 only supports the new "SDK" format. 
https://github.com/damianh/LibLog#availability-for-old-csproj-format
https://github.com/damianh/LibLog/issues/237
https://github.com/damianh/LibLog/issues/220
https://github.com/damianh/LibLog/issues/202

**Comment by chiefengineer** [comment]
Thanks! Learn something new every day. Don't pay much attention to the
"upgrade" path when it comes to framework versions, when a new version of
the .NET Framework comes out, I generate new .csproj files for just those
reasons and move the library code over, don't want to have to worry about
cleaning up old messes and removing cruft.
This should be the "new" format, the .csproj files were created
specifically for this project using VS2019 Enterprise after the install of
.NET Full Framework 4.8.
No carryover from an older format, not an "upgrade", not a "refactoring".
However, I have not yet switched to the "PackageReference" mode of package
management simply because of the stated incompatibilities with some
applications (see:
https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files
about
half way down, specifically the following quote: "ASP.NET apps targeting
the full .NET Framework include only limited support
<https://github.com/NuGet/Home/issues/5877> for PackageReference. C++ and
JavaScript project types are unsupported."). When (if) that goes away, I'll
make the switch.
If I need to I can supply a solution that exhibits the problem.
One other thing - the attempted install was not using "dotnet" but using
the integrated functionality as supplied by VS2019 (went to the NuGet tab
and attempted to install from there).

**Comment by damianh** [comment]
Yeah the transition wasn't the smoothest and understand your approach. I couldn't support the new project format for quite a while after it was initially released (given the nature of this source code package).

It's not possible to support both formats in the one package. If you remain on the old format, for whatever reasons, the 4.x line still supports it (until it stops working - am not officially maintaining that version line).

> the attempted install was not using "dotnet" but using the integrated functionality as supplied by VS2019

This is effectively the same for new sdk project formats.

Closing as there isn't anything specifically to be done.
