### ISSUE TITLE
LibLog alignment with Microsoft.Extensions.Logging

### ISSUE THREAD

**Issue by raxuser100** [damianh/LibLog#256]
Does LibLog offer operation within the  `Microsoft.Extensions.Logging` framework. I guess they are competing abstractions but wondered if the two could be aligned. 

A custom `Microsoft.Extensions.Logging.ILogger<T>` wrapper around `ILog `perhaps?

Perhaps I am missing something here as new to logging. My clients are imposing that the logger instance used throughout library classes, must implement the interface `Microsoft.Extensions.Logging.ILogger<T>`.

Any assistance please on how to create this instance via LibLog?

Please see my question created on [Stackoverflow ](https://stackoverflow.com/questions/57593568/for-library-classes-does-liblog-work-with-microsoft-extensions-logging-framework)

**Comment by snakefoot** [comment]
Think it should be possible to create a LibLog-Provider that takes MEL `ILoggerFactory` as input parameter.

`ILoggerFactory.CreateLogger(string name)` will return a named logger-object, then just use that to make the implementation (similar to the other LibLog-Providers).

**Comment by damianh** [comment]
As per #270, I am recommending (though I don't necessarily _like_) that lib authors use `Microsoft.Extensions.Logging.Abstractions` from now. It's shipped with the Core SDKs and is now effectively the "System" logging interface. As such I won't be adding any specific support to MEL within `LibLog`. Though a gist / wiki with an example provider for older libs still using LibLog to log to MEL would be useful.
