### ISSUE TITLE
LoupeLogging tests are not asserting if actual message was written.

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#26]
All of the log provider tests assert that the correct log message was written by using in-memory logging targets. i.e. [NLog](https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests/LogProviders/NLogLogProviderLoggingTests.cs#L46) and [Log4Net](https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests/LogProviders/Log4NetLogProviderLoggingTests.cs#L42).

The [LoupeLoggingProviderTests](https://github.com/damianh/LibLog/blob/master/src/LibLog.Tests/LogProviders/LoupeLogProviderLoggingTests.cs#L37) are missing these however.

@kendallmiller can you point me in the direction on how to create a Loupe in-memory target so I can assert the messages? Thx!

**Comment by kendallmiller** [comment]
This is a bit complicated with Loupe - the Loupe API doesn't expose its targets so you can't swap in an in-memory target.  (This was done to minimize the surface area of the API).  That said, there is a way to check this more-or-less:  There is an event raised when warnings, errors, or critical messages are logged (Log.MessageAlert).  So it's possible to test that warnings, errors, and critical messages are being logged by subscribing to that event handler, logging messages, then seeing that they are raised by MessageAlert.  That said, because of the asynchronous nature of Loupe you have to allow a little time from when you log until they are raised to check for it.  

Later this year we're going through our first major API expansion in a few years and I'll talk with the team about exposing our target libraries so this is easier.

**Comment by damianh** [comment]
Ok. Will leave this open until we have a solution.

**Comment by damianh** [comment]
Hi @kendallmiller, was an in-memory target developed?

**Comment by kendallmiller** [comment]
On our list for this summer, along with .Net core.  We will have a way of testing this a bit sooner.

On Mar 29, 2016, at 11:23 AM, Damian Hickey <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @kendallmiller<https://github.com/kendallmiller>, was an in-memory target developed?

**Comment by damianh** [comment]
Cool thx!

**Comment by damianh** [comment]
@kendallmiller This has been open for a while... :) Did the ,net core port happen and the in-memory target?

**Comment by kendallmiller** [comment]
We are in the midst of it right now - much delayed as we waited for .NET Core to settle down.  We'll have a new Loupe Agent out on GitHub within a few weeks, and while this initial port doesn't have this feature (not in full) the follow on to it will.  So, embarrassingly we're just about exactly a year behind what I thought.    

I'll update this ticket as soon as we get there.

**Comment by damianh** [comment]
I think everyone is a year (or two) behind on where we'd thought we would be regarding .net core ;)

**Comment by damianh** [comment]
Am considering new version to coincide with NetStandard 2.0. I can't continue to support Loupe without tests (and ability to have an in-memory target which seems to be blocking the tests).

**Comment by kendallmiller** [comment]
I understand; we're working on our .NET Standard port with that capability, but you probably are on a faster timeline than we are.  We can add ourselves back on the other side when we publish our .NET Standard version if we have to.  Of course, if feasible we'd like to stay included until we can address this.

**Comment by damianh** [comment]
I'm aligning a bit with NetStandard2 release, which is "Q3 2017". Lets analyse as we close thing. (And thanks for being responsive!)

**Comment by kendallmiller** [comment]
We're getting close to shipping an updated Agent with .NET Core support with a way to do this, so we're getting there.  As soon as we have an alpha package with that support I'll update LibLog.

**Comment by damianh** [comment]
Great!

**Comment by kendallmiller** [comment]
OK, Step one of three done on this:  We have the new [open source Loupe Agent for .NET Core](https://github.com/GibraltarSoftware/Loupe.Agent.Core).  Now on to step two - make it possible to unit test the log messages with the new API that's exposed. (step three is integrate that back with LibLog).  We'll get on it!

**Comment by damianh** [comment]
I've ported LibLog to loupe agent for .netstandard 2.0. I don't know if it works yet. Is there an in-memory sink I can assert some tests against? Otherwise I think I'll have to pull support for this from next release as consumers would have a false sense that this will work.

**Comment by kendallmiller** [comment]
I'll check it to confirm and will add unit tests to verify it.

**Comment by kendallmiller** [comment]
I've added unit tests after updating to a new version of Loupe that provides a hook to get messages.
