### ISSUE TITLE
Minimum framework compatibity version

### ISSUE THREAD

**Issue by advapiIT** [damianh/LibLog#260]
Hello,
I'm trying to use LibLog 5.0.6 on a Framework 4.6.1 library, but it doesn't install.. where can I read which version of the framework is LibLog compatible with?

Thanks

**Comment by bartelink** [comment]
>this is handled transparently by the new dotnet sdk as of LibLog version 5.0.0
are you using new a new style project with the dotnet sdk ?

**Comment by advapiIT** [comment]
no, on an old 4.6.1 library...

**Comment by bartelink** [comment]
this has come up in the issues in recent times, suggest looking for those threads. As per the readme, the advice is to use < 5 in that instance. (there may be other hackarounds suggested in those issues too)
(Personally, I'd highly recommend to port projects to the new SDK sooner than later)

**Comment by damianh** [comment]
https://github.com/damianh/LibLog#availability-for-old-csproj-format

I don't have any way to make this easier/pit-of-success. There is no facility to detect attempting to install in old csproj format and give a nice error.
