### ISSUE TITLE
Indicate logger preference

### ISSUE THREAD

**Issue by asherber** [damianh/LibLog#262]
So I've fallen afoul of the "gotcha" referenced in the wiki -- the project that consumes my library references multiple log providers, and the order in which LibLog looks for providers means it doesn't pick the one I want.

I would love to be able to do at least one of these things:

1. From within my library project, specify a different order for `LogProviderResolvers`
2. From my consuming project, specify a different order for `LogProviderResolvers`
3. From my consuming project, specify exactly which provider to use

**Comment by asherber** [comment]
I see that the various LogProviders have a `ProviderIsAvailableOverride` property that I can use to force disable a provider. It's `internal`, so if I want to make it available outside my library I need to add some kind of library function.

I also see `LogProvider.SetCurrentLogProvider()`, which is `public`, but I don't see any way of actually creating a `LogProvider` from the consuming project.

**Comment by asherber** [comment]
I'm happy to work on a PR, with some guidance on which approach would best fit the library.

**Comment by damianh** [comment]
Hi @asherber as per #270, my advice to you now is to take a dependency on Microsoft.Extensions.Logging.Abstractions. It's now the standard/defacto interface in .NET ecosystem. As such I won't be taking any further changes, thanks for the offer.

Note, if you do wish to continue using LibLog in your project then just copy the code in (which is what LibLog effectively did anyway) and adjust to your needs. Yay OSS :)
