### ISSUE TITLE
LibLog 5.0.8 Release Notes

### ISSUE THREAD

**Issue by snakefoot** [damianh/LibLog#274]
#223 - Improve Type lookup when using ILRepack
#233 - Fixed NLogLogProvider to not perform reflection for every logevent
#234 - Minor variable rename in ColoredConsoleLogProvider
#266 - Fixed XML docs in ILogProvider and LogProvider
#271 - LibLogException excluded from code coverage, and internal when LIBLOG_PROVIDERS_ONLY

**Comment by damianh** [comment]
Applied and released. Cheers for the help!

https://github.com/damianh/LibLog/releases/tag/v5.0.8
https://www.nuget.org/packages/LibLog/5.0.8

**Comment by snakefoot** [comment]
Thank for the release. Will try it out

**Comment by snakefoot** [comment]
Performance is excellent when using LibLog with NLog, and it produces good output. Thank you for the fishes :)
