### ISSUE TITLE
Log4Net Log level initialized to null

### ISSUE THREAD

**Issue by cmatskas** [damianh/LibLog#31]
Hi @damianh, thanks for the excellent library. Trying to write a blog about it and created a sample console project with log4net to test it out, but the logger is initialized with `level=null` However, the `EffectiveLevel` is set correctly to what's configured in the log4net.config file. Please tell me it's something silly I did an not a bug? Happy to supply any files you may need, though the setup is pretty basic. Any help would be really appreciated.

**Comment by damianh** [comment]
Can you put the example in a github repository somewhere and I'll take a look? Thx.

**Comment by cmatskas** [comment]
Will do tonight. Thanks for the quick response :)
CM





        

	



On Mon, Feb 2, 2015 at 6:48 AM -0800, "Damian Hickey" <notifications@github.com> wrote:












Can you put the example in a github repository somewhere and I'll take a look? Thx.

**Comment by cmatskas** [comment]
Hi Damian,


Many thanks for looking into this. If it is something silly I did, I will kick myself in the face - better this than a bug 😊


https://github.com/cmatskas/LibLogSample/


CM





Sent from Windows Mail





From: Damian Hickey
Sent: ‎Monday‎, ‎2‎ ‎February‎ ‎2015 ‎14‎:‎48
To: damianh/LibLog
Cc: chris@towzietyke.co.uk





Can you put the example in a github repository somewhere and I'll take a look? Thx.

**Comment by damianh** [comment]
Hi, it's going to be the weekend before I get to have a look.

**Comment by cmatskas** [comment]
Hi @damianh that's fine. I am sure you are a busy man. As long as we can get to the bottom of it, I'm happy to wait. Many thanks and I look forward hearing back from you.

**Comment by damianh** [comment]
https://github.com/damianh/LibLogSample/blob/master/LibLogSample/Program.cs#L19

When using log4net directly nothing happens either. Is there a configuration problem?

**Comment by damianh** [comment]
Fixed it https://github.com/damianh/LibLogSample/commit/ac454b636885f5d8474995068ac36e3966ffa848

![image](https://cloud.githubusercontent.com/assets/57436/6096153/019c876c-af83-11e4-93c3-801a82ddc797.png)
