### ISSUE TITLE
FormatException when message containes { } inside

### ISSUE THREAD

**Issue by maciejw** [damianh/LibLog#34]
given this message "Query language substitutions: {'true'='1', 'false'='0', 'yes'=''Y'', 'no'=''N''}" LogMessageFormatter.SimulateStructuredLogging throws format exception

I think its not a responsibility of a caller to escape {}. This line came from nhibernate. it was tested in 3.1 version.

**Comment by damianh** [comment]
Can I get a test case that demonstrates this? That would be very helpful, thanks. :wink:

**Comment by maciejw** [comment]
here you go:)

```c#
        [Test]
        public void Should_log_message_with_curly_brackets()
        {
            ILog log = LogProvider.GetCurrentClassLogger();

            StringBuilder sb = new StringBuilder();

            Console.SetOut(new StringWriter(sb));

            log.Debug("Query language substitutions: {'true'='1', 'false'='0', 'yes'=''Y'', 'no'=''N''}");

            Assert.IsTrue(sb.ToString().Contains("Query language substitutions: {'true'='1', 'false'='0', 'yes'=''Y'', 'no'=''N''}"));
        }

```

**Comment by damianh** [comment]
Thank you!

**Comment by Erwinvandervalk** [comment]
Just created PR to solve this issue: https://github.com/damianh/LibLog/pull/39

**Comment by damianh** [comment]
Thanks @Erwinvandervalk!
