### ISSUE TITLE
LoupeLogger skipLevel

### ISSUE THREAD

**Issue by llusetti** [damianh/LibLog#41]
Is it me or the default skipLevel in the loupeLogger should be set to 2 ?
With the default setting of 1 i get the all my log locations refer to LigLog.cs

**Comment by kendallmiller** [comment]
I'll investigate - it should be the number of stack frames to get out of the log system.

**Comment by llusetti** [comment]
Exactly! With 1 you go to the LoupeLogProvider with 2 you go to the actual line that logged the message.

To me it makes sense the second case not the first.

**Comment by kendallmiller** [comment]
Have you compared release & debug mode?  I'm wondering if this is an issue of a difference in method inlining.

**Comment by llusetti** [comment]
Same result with visual studio in DEBUG or RELEASE mode
The location reported by Loupe with skipLevel = 1 is
Line 516 of file '...\Core.Common\App_Packages\LibLog.3.1\LibLog.cs'

**Comment by kendallmiller** [comment]
I'm testing the fix now, will have a PR soon.

**Comment by kendallmiller** [comment]
I'm getting different results in Debug vs. Release builds (with the latest code), probably due to variable compiler inlining of the various logging methods in LibLog.  Can you try this version to see if it works for you (in debug & release mode)?  

https://github.com/kendallmiller/LibLog

**Comment by llusetti** [comment]
I built and installed the nuget package, in debug everything is ok but in release mode location refers to '..\Core.Common\App_Packages\LibLog.4.0\LibLog.cs' as before.

Did i mess something or it's right I had to define a LIBLOG_PUBLIC compile to make interface public ?

**Comment by damianh** [comment]
Any code that relies on stack trace to get callsite info is always going to
be problematic in release mode.

And then... .net native ;)
On 16 Mar 2015 17:01, "llusetti" <notifications@github.com> wrote:

I built and installed the nuget package, in debug everything is ok but in
release mode location refers to
'..\Core.Common\App_Packages\LibLog.4.0\LibLog.cs' as before.

Did i mess something or it's right I had to define a LIBLOG_PUBLIC compile
to make interface public ?

—
Reply to this email directly or view it on GitHub
<https://github.com/damianh/LibLog/issues/41#issuecomment-81760587>.

**Comment by llusetti** [comment]
To be honest is not a great problem I will set the skipframe myself to 2 and see how it goes, I'm not scared of some tweaking :)

I really like the independent logging solution you have built, I am trying to remove completely Loupe from my solution but I have to find (or craft) a decent unhandled exception manager and live log viewer. Any suggestion ?

**Comment by kendallmiller** [comment]
Depending on whether you goal is to support all features regardless of log system or not you could just invoke the Loupe Live Viewer via reflection, or alternately fire up the out-of-process Loupe Viewer (available on NuGet) if people are using Loupe.

If your goal is to migrate away from Loupe, I'd love to know why (vested interest of course - it's my team's full time work!); if you could drop us a line at support @ gibraltarsoftware.com I'd appreciate it.

**Comment by kendallmiller** [comment]
To Damian's comment - He's right that using a fixed stack level is not a great approach; when I added Loupe to LibLog I was trying hard to minimize changes.  There are two other ways this can be made bulletproof - one is to prevent the compiler from inlining the intervening methods (which has a theoretical, but not practical, perf impact) and the other would be to use a more elaborate class we have for determining the method source which lets you filter out classes & namespaces that it should ignore when traversing back the call stack.  That has the downside of adding another class and a bit of complexity at this point, but we're likely to add it to our public API to make this better.

**Comment by llusetti** [comment]
To kendall: I didn't express myself in the right way, I love loupe and I was a paying customer when it was named gibraltar and I do not want to remove it. But since my application is composed of many projects (desktop app, 2 web applications) I want the dependency on Loupe to be only in the entry assembly and not in all the libraries.

I'm also interested in the Loupe Server, now that my user base has grown, but that's a different story :) I will get in touch with the support department if I have any questions.

**Comment by damianh** [comment]
When implementing that, give a thought to ilmerge /internalize. Type names
(and I think namespaces) can change.

**Comment by damianh** [comment]
I believe this is fixed via #44
