### ISSUE TITLE
Custom event properties

### ISSUE THREAD

**Issue by michaeldotknox** [damianh/LibLog#45]
I'm using LibLog as part of an IdentityServer implementation and am using NLog as my logging provider.  We need to log a number of custom fields to be able to troubleshoot potential issues with users.  NLog allows custom fields with a Properties dictionary and the event-context layout renderer.  Is this supported via LibLog?

I don't see anything that would allow this, but I may have missed it.

Thanks so much.

**Comment by damianh** [comment]
This is always going to be a problem with lowest-common-denominator abstractions. Each feature should work in all implementations.

I din't think I'll be able to implement something to support that specific scenario. Could you achieve what you want through structured logging and/or mapped/nested diagnostic contexts?

**Comment by michaeldotknox** [comment]
I was afraid you would say that.

I can get around it with more detailed error messages, but it would have been nice to directly add those values into a field.  But I'll keep digging and maybe I can find an elegant solution.

**Comment by damianh** [comment]
Am open to suggestions / solutions but can't see any other way than what
I've already said. It sounds like you have a hard dependency on a logging
fwk which is fine from a top-level / exe pov but arguable from a library
pov.

Closing this now. If any approaches emerge, can re-open.

#close
