### ISSUE TITLE
Mono compiler warnings

### ISSUE THREAD

**Issue by adamralph** [damianh/LibLog#46]
> App_Packages/LibLog.3.1/LibLog.cs(652,38): error CS0414: Warning as Error: The private field `ScriptCs.Logging.LogProviders.NLogLogProvider.NLogLogger._logger' is assigned but its value is never used

> App_Packages/LibLog.3.1/LibLog.cs(871,38): error CS0414: Warning as Error: The private field `ScriptCs.Logging.LogProviders.Log4NetLogProvider.Log4NetLogger._logger' is assigned but its value is never used

**Comment by adamralph** [comment]
After looking at the code, it appears the warning is nonsense. The fields are used. BUT... they are `dynamic`. Poor old mono compiler...

**Comment by damianh** [comment]
Just as well the mono compiler is going dodo I guess...

**Comment by damianh** [comment]
So... what can I do here?

**Comment by adamralph** [comment]
Nowt :wink:
