### ISSUE TITLE
GlobalContext/ThreadContext

### ISSUE THREAD

**Issue by darkl** [damianh/LibLog#49]
Hi,
Nice project!

I have a question - I want to set some GlobalContext/ThreadContext variables in case the user uses log4net. I can't see any method which supports this. Castle's logging interface seem to support this using an interface named IExtendedLogger which has a property that allows access to these contexts.

Are there any plans to add support for this to LibLog? will you accept a pull request for this kind of feature?

Thanks

**Comment by damianh** [comment]
Hi, glad you like it. :)

On the other hand, LibLog is specially designed for Libraries. It's questionable whether doing something like adding items to Global/ThreadContext from within a library is even a good idea.

Any new features would have to work across all supported loggers (EntLib doesn't support NDC/MDC and that rustles me a bit :disappointed: ), so if this is available across all, I'd consider it. No guarantees though, I'm really focused on keeping ILog and LogProvider as simple as possible.

Also, does GlobalContext/ThreadContext work in the async / task world?

**Comment by darkl** [comment]
Hi, Thanks for the quick reply.

About my scenario: My library allows writing some server-side applications. Every client that connects to the server gets a session id. I want to make the session id of the current client (the client who requested the current request) to be available for users, so they can track which request came from which client.

I think using ThreadContext is suitable for this case, but if you have other suggestions I'd be happy to consider them.

**Comment by damianh** [comment]
Thread contexts (thread local storage) is always going to sketchy in async
apps.

Nested and/ or mapped diagnostic contexts should fill your need. LibLog
supports these.

**Comment by damianh** [comment]
Just realised I forgot to update the readme with instructions on those.
Will do so in the morning.

**Comment by darkl** [comment]
It seems that mapped diagnostic contexts are deprecated
<http://logging.apache.org/log4net/release/sdk/log4net.MDC.html>, but it
also says that the current implementation forwards to
ThreadContext.Properties, which is exactly what I wanted.

Thanks again for your help!

**Comment by darkl** [comment]
The only disadvantage is that you can't store any object using the MDC
class (only strings are supported), in oppose to
ThreadContext/GlobalContext where you can.

**Comment by damianh** [comment]
Cool!
