### ISSUE TITLE
Be able to Disable all logging for a given Lib

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#50]
"I want to just disable console logging, actually all logging, in tests. I'd like Console logger to remain in use in shipped assembly.", paraphrased from @leastprivilege 

I propose a `public static void LogProvider.Disable()` and that will mean for every subsequent call to `GetLogger()` a Noop logger is returned. I can see this being of use to Lib consumers who may just want to turn off logging for a lib they are consuming.

Point of note - this will be static mutable state. This needs to be considered when leveraging parallel testing.

A corresponding `public static void LogProvider.Enable()` would be needed also.

**Comment by leastprivilege** [comment]
maybe also have a env var - e.g. "LibLog_Disable" - which instructs liblog to always to Noop logger.

**Comment by leastprivilege** [comment]
I think thats too noisy for automated builds
https://ci.appveyor.com/project/leastprivilege/thinktecture/build/2.0.9

**Comment by damianh** [comment]
Backwards compatible API change, so this is moving to v4.1.0

**Comment by damianh** [comment]
@leastprivilege are you still using this feature?

**Comment by leastprivilege** [comment]
no
