### ISSUE TITLE
automatically test new logging nugets

### ISSUE THREAD

**Issue by SimonCropp** [damianh/LibLog#51]
I am not sure if you already do this but it is probably valuable for you to setup a custom daily CI build that does a nuget update on all the logging lobs your support and runs through your standard suite of tests. This means as soon as a new incompatible version of any of those libs is released you will know in in an automated way.

**Comment by damianh** [comment]
Agreed. How do I nuget update outside of VS? I remember looking at this [some time ago](https://nuget.codeplex.com/workitem/902) and I don't think the situation has changed. But knowing you, you'll have a trick up your sleeve :)

**Comment by gep13** [comment]
Am I missing something, or is this:

https://docs.nuget.org/consume/command-line-reference#update-command

not what you are after?

**Comment by damianh** [comment]
It looks like it.. but does up date hintpaths etc in csprojs?

**Comment by gep13** [comment]
ooo, good question.  Honestly not sure, never actually tried it.  Your question triggered a memory that I had seen the ```update``` command, but never had the need to use it :smile:

**Comment by damianh** [comment]
I guess I'll try it :)

**Comment by damianh** [comment]
Marking it as help-wanted just incase it scratches someone itch and because I can't see myself getting to this anytime soon.

Any solution should be entirely command line driven and not require VS on build server.

**Comment by damianh** [comment]
Really old one this. I've decided to keep it open and consider it when targeting NetStandard2.0. Updating nuget packages from CLI is much easier now...

**Comment by SimonCropp** [comment]
u can now do a wild card ref and just have a nightly build

**Comment by damianh** [comment]
Event easier! Cheers

**Comment by damianh** [comment]
Going to close this as A) I haven't done it! and B) the various logging libs seem to be very careful of their backwards compatibility / API changes so need appears low.
