### ISSUE TITLE
LogProvider.GetCurrentClassLogger() vulnerable to JIT inlining

### ISSUE THREAD

**Issue by adamralph** [damianh/LibLog#52]
See https://github.com/scriptcs/scriptcs/pull/1009#issuecomment-88656779

As I began to mention last night, the way we're using LibLog in scriptcs is rather unusual, resulting in us providing `ILog` extension methods. Anyway, one of those methods is a direct equivalent of `LogProvider.GetCurrentClassLogger()`.

Due to the conclusions that the JIT compiler arrives at, the extension method happens to get inlined which alters the stack and caused the `StackFrame` stuff to blow up with an NRE. The cause of the issue was very hard to determine because the stack trace was very misleading. I just happened to notice that we were only getting the failure in Release and not Debug, so I took a punt on that method, shoved `[MethodImpl(MethodImplOptions.NoInlining)]` onto it, and hey presto, it fixed the problem.

Anyway, I'm not sure if anyone's run into this with LibLog. I guess not, and that's probably just a lucky outcome of the JIT, but I wonder if it may be worth putting the attribute on that method now to insulate it against a different JIT heuristic in the future. After all, .NET 4.6 is getting a new 64-bit JIT and who knows what that might do, in it's final form, against this method? I suppose if you're ever playing with `StackFrame` in a method like this it's probably a very good idea to deterministically prevent inlining to keep the method behaving as you want it to.

**Comment by appetere** [comment]
I've run into this with [Thinktecture IdentityServer3](https://github.com/identityserver/IdentityServer3)

A similar issue is also highlighted by a [Redgate article](https://www.simple-talk.com/blogs/2010/02/18/why-not-to-use-stacktrace-to-find-what-method-called-you/)

In my case, the code was deployed to Windows Server 2012 R2, x64, with .NET 4.5.2.

In `LogProvider` calling the method below resulted in null value from some part of `stackFrame.GetMethod().DeclaringType` (I can't say which as is insufficient info from stack trace):
```
public static ILog GetCurrentClassLogger()
{
     var stackFrame = new StackFrame(1, false);
      return GetLogger(stackFrame.GetMethod().DeclaringType);
}
```

**Comment by adamralph** [comment]
@appetere thanks for chiming in. It seems this is a genuine issue then.

**Comment by damianh** [comment]
Ok guys thx; this will need to be fixed so.

I wont get to it before next week though.

**Comment by appetere** [comment]
For me, it may be that I was calling `GetCurrentClassLogger` from a class constructor, rather than assigning the result directly to a `private static readonly` field - see [leastprivilege comment](https://github.com/IdentityServer/IdentityServer3/issues/1144#issuecomment-89003586)

I'll try it using the static next week and leave a comment with how I get on.

**Comment by damianh** [comment]
In build 103 on ci feed https://www.myget.org/F/dh/

**Comment by damianh** [comment]
Re-opening issue because of redgate article.. It appears GetCurrentClassLogger is sketchy even if I prevent MethodInlining ?

**Comment by adamralph** [comment]
This should be milestone 4.1.0

**Comment by appetere** [comment]
Just for your information, my calls to GetCurrentClassLogger now work fine when deployed to x64 server, after assigning the result to a static variable.

So, using the intended pattern, I no longer have the problem I thought I did.
