### ISSUE TITLE
4.0.2 not tagged on master

### ISSUE THREAD

**Issue by adamralph** [damianh/LibLog#55]

**Comment by damianh** [comment]
I'll tag it when I release it to nuget.org. Put it this way, work on 4.0.2 has _started_ but isn't _finished_.

**Comment by adamralph** [comment]
You pushed it nuget yesterday https://www.nuget.org/packages/LibLog/4.0.2

**Comment by damianh** [comment]
https://github.com/damianh/LibLog/tree/v4.0.2
