### ISSUE TITLE
Default to System.Diagnostics tracing when no console available (and no other providers)

### ISSUE THREAD

**Issue by leastprivilege** [damianh/LibLog#61]
Wouldn't that make sense?

**Comment by leastprivilege** [comment]
maybe not. i just switched to serilog and use their sys.diag support

**Comment by damianh** [comment]
As you mention, most (all?) of the supported libraries support System.Diagnostics tracing. They all support console too of course...

Will leave this open, see if anyone else weighs in with yays or nays.

**Comment by damianh** [comment]
As discussed in #62, LibLog shouldn't be doing any actual logging. Closing as wontfix.

**Comment by ocdtrekkie** [comment]
I found this issue digging around, and... guessing this means I'm crud out of luck: I don't use any logging frameworks and don't want to add any. I have a System.Diagnostics trace listener. But I'm trying to see Quartz.NET's logs... and they use LibLog and basically just say "look at LibLog on how to configure your logging".

**Comment by StevenBonePgh** [comment]
See: https://github.com/damianh/LibLog/wiki/Extending
You will need to implement LibLog's ILogger which is exposed in that library (likely in the Quartz.Logging namespace) to call into system.diagnostics.*.  Then call Quartz.NET's exposed static method LogProvider.SetCurrentLogProvider() to your implementation at app startup.

And, yes, you ARE using a logging framework - System.Diagnostics - it is not one that is out-of-box for liblog as you never can tell from the outside if someone is 'willingly' using it or not.  People don't generally consider it a logging framework (as they usually mean an EXTERNAL logging framework).  System.Diagnostics just really doesn't cut it these days for all but the most superficial logging needs.

**Comment by ocdtrekkie** [comment]
FWIW, to share what I did in case someone else needs something similar:

I took Quartz's "Adding logging" entry to patch stuff over to the console: https://www.quartz-scheduler.net/documentation/quartz-3.x/quick-start.html#adding-logging which I converted to VB, borrowed from damianh's gist mostly for the switch statement inspiration: https://gist.github.com/damianh/fa529b8346a83f7f49a9

My end result is here: https://github.com/ocdtrekkie/HAController/commit/36dd442e19e166c97f703d08dd622ad1644a4d84

It happily piles all of my Quartz.NET logging into VB's standard application log setup. :D
