### ISSUE TITLE
Remove the ConsoleLogger

### ISSUE THREAD

**Issue by damianh** [damianh/LibLog#62]
`LibLog's` goal is to provide a simple logging abstract and support for several of the most popular loggers. Of course, all these loggers have console sinks. Does having a `ColouredConsoleLogger`step outside `LibLog's` remit? Should it, or should it not, be doing any actual output at all (Console, System.Diagnostics, etc)?

**Comment by leastprivilege** [comment]
I think you got a point here. It is supposed to be a logging abstraction - not a logger itself.

Then we wouldn't need environment variables to control it ;)

**Comment by adamralph** [comment]
(Cross post from [gitter](https://gitter.im/damianh/LibLog))
> it's a tough one. One hand, I like the getting the immediate logging when I plug it in during dev. On the other, it very quickly becomes a necessity to switch it off

On balance, it probably makes sense to remove it. It should be very cheap to install one of the logging frameworks and configure a console logger.

**Comment by damianh** [comment]
Pinging @danbarua as the original contributor of the console logger for opinion :)

**Comment by damianh** [comment]
Hypothetical question, if it were to be removed, is it a breaking change? There would not be any API changes as exposed via consuming lib and I'd probably keep the ability to disable logging as-is. I'm inclined to say that it isn't.

**Comment by adamralph** [comment]
Agreed. Not breaking. It has little use in production and I'd be very surprised if anyone were relying on it for anything.

**Comment by adamralph** [comment]
If it's removed, I wonder if I should remove the `NullLogProvider` that I've PR'd for scriptcs... when summarising the changes the only justification I could think of for it was a cheap way to switch off logging without installing a logging framework.

**Comment by damianh** [comment]
Am inclined to agree.

**Comment by danbarua** [comment]
Agreed, it's of no use in production, I only use it in example code/demo projects for libs that I'm working on, where it probably should live.

**Comment by damianh** [comment]
Thx Dan ;)

I'll remove it in next minor version and gist/wiki it so people can drop it
into their test /demo projects.

**Comment by adamralph** [comment]
:+1:

**Comment by leastprivilege** [comment]
done yet?

**Comment by damianh** [comment]
4.2.0-build00139 on CI feed.
