### ISSUE TITLE
Support extension methods for string format

### ISSUE THREAD

**Issue by GeertvanHorrik** [damianh/LibLog#71]
An example (taken from https://github.com/Catel/Catel/blob/develop/src/Catel.Core/Catel.Core.Shared/Logging/Extensions/LogExtensions.debug.cs#L30):

```
        /// <summary>
        /// Writes the specified message as debug message.
        /// </summary>
        /// <param name="log">The log.</param>
        /// <param name="messageFormat">The message format.</param>
        /// <param name="args">The formatting arguments.</param>
        public static void Debug(this ILog log, string messageFormat, params object[] args)
        {
            string message = messageFormat ?? string.Empty;
            if (args != null && args.Length > 0)
            {
                message = string.Format(message, args);
            }

            log.Debug(message);
        }
```

**Comment by damianh** [comment]
Looks reasonable. Will certainly take a PR with this. 

Do you have these currently working with LibLog?

**Comment by GeertvanHorrik** [comment]
See https://github.com/GitTools/GitTools.Core/blob/develop/src/GitTools.Core/Logging/Extensions/LogExtensions.cs

They might cause circular references (what's the difference between Debug(string) and Debug(string, params), but hopefully the compiler is smart enough.

**Comment by damianh** [comment]
Cool, will see about pulling that in.

**Comment by gwicksted** [comment]
If you support R# attributes, this one is nice for code completion:

`[StringFormatMethod("messageFormat")]`

Unfortunately their language extensions for string literals does not include the format string hint... so it requires you use the attribute and thus requires:

a) `using JetBrains.Annotations;`

b) copying the attribute code into LibLog's file as done in [Common.Logging.Core](https://github.com/net-commons/common-logging/blob/master/src/Common.Logging.Core/Logging/Factory/ResharperAnnotation.cs)

**Comment by damianh** [comment]
Closing this due to age. If anyone would like to see this, then a PR would be very welcome.
