### ISSUE TITLE
Don't lock GetType() values.

### ISSUE THREAD

**Issue by IDisposable** [damianh/LibLog#75]
https://github.com/damianh/LibLog/blob/dev/src/LibLog/LibLog.cs#L1156 might not be a good plan, see http://buffered.io/posts/always-question-the-source-aka-dont-lock-on-type-objects/

**Comment by damianh** [comment]
Thanks for reporting!

**Comment by damianh** [comment]
Looks problematic alright: https://www.mail-archive.com/bdotnet@groups.msn.com/msg06816.html

@lahma , this is code you have contributed. Why is the lock there? Will this cause contention / perf issue? If it needs to remain, can this be fixed?

**Comment by lahma** [comment]
I'm sure one can also use instance variable for locking, so the GetType() should be unnecessary all right.

**Comment by damianh** [comment]
I understand why the lock is there - thread safe lazy initialization...
