### ISSUE TITLE
Would be nice with a factory for logproviders that work accross libs that use liblog

### ISSUE THREAD

**Issue by s093294** [damianh/LibLog#77]
In our solution we use idsrv3 and a few of my own libs that all have used liblog.

From the developer point of view when using multiply libs that use liblog one has to configure at startup the logproviders for all of them.
```
ns1.Logging.LogProvider.SetCurrentLogProvider(...);
ns2.Logging.LogProvider.SetCurrentLogProvider(...);
ns3.Logging.LogProvider.SetCurrentLogProvider(...);
ns4.Logging.LogProvider.SetCurrentLogProvider(...);
```
Due to it's not a shared library that is used I need to implement my log provider for each of the using libs since they have their own dll ect. The problem that i have is the enum for loglvl that exists in all libs that use liblog. Maybe someone can do some magic using a primitive type?

If someone has a workaround with reflection that would work for me also. 

Example:

    public class MultiDiagnosticsTraceLogProvider : ILogProvider, 
        SInnovations.ConfigurationManager.Logging.ILogProvider, 
        SInnovations.Azure.MessageProcessor.Core.Logging.ILogProvider, 
        SInnovations.Azure.TableStorageRepository.Logging.ILogProvider
    {
        public Logger GetLogger(string name)
        {
            return new DiagnosticsTraceLogger(name).Log;
        }
        SInnovations.ConfigurationManager.Logging.Logger SInnovations.ConfigurationManager.Logging.ILogProvider.GetLogger(string name)
        {
            return new DiagnosticsTraceLogger(name).Log; //this cannot be reused.
        }

        SInnovations.Azure.MessageProcessor.Core.Logging.Logger SInnovations.Azure.MessageProcessor.Core.Logging.ILogProvider.GetLogger(string name)
        {
            throw new NotImplementedException();
        }

        SInnovations.Azure.TableStorageRepository.Logging.Logger SInnovations.Azure.TableStorageRepository.Logging.ILogProvider.GetLogger(string name)
        {
            throw new NotImplementedException();
        }
    }

and 

    public class DiagnosticsTraceLogger : ILog
    {
        private readonly string _name;
        private static string fullPattern = Regex.Replace(DateTimeFormatInfo.CurrentInfo.FullDateTimePattern, "(:ss|:s)", "$1.fff");
        
        public DiagnosticsTraceLogger(string name)
        {
            this._name = string.Format("[{0}]", name);
        }
        
        public bool Log(Ascend.Common.Logging.LogLevel logLevel, Func<string> messageFunc, Exception exception = null, params object[] formatParameters)
        {
            if (messageFunc != null)
            {
                if (exception == null)
                {
                    string message = string.Format("{0}: {1} -- {2}", this._name, DateTimeOffset.UtcNow.ToString(fullPattern), string.Format(messageFunc(), formatParameters));
                    TraceMsg(logLevel, message);
                }
                else
                {
                    string str2 = string.Format("{0}: {1} -- {2}\n{3}", new object[] { this._name, DateTimeOffset.UtcNow.ToString(fullPattern), string.Format(messageFunc(), formatParameters), exception });
                    TraceMsg(logLevel, str2);
                }
            }
            return true;
        }
        
        private static void TraceMsg(Ascend.Common.Logging.LogLevel logLevel, string message)
        {
            switch (logLevel)
            {
                case Ascend.Common.Logging.LogLevel.Trace:
                case Ascend.Common.Logging.LogLevel.Debug:
                    Trace.WriteLine(message, logLevel.ToString());
                    return;
                
                case Ascend.Common.Logging.LogLevel.Info:
                    Trace.TraceInformation(message);
                    return;
                
                case Ascend.Common.Logging.LogLevel.Warn:
                    Trace.TraceWarning(message);
                    return;
                
                case Ascend.Common.Logging.LogLevel.Error:
                    Trace.TraceError(message);
                    return;
                
                case Ascend.Common.Logging.LogLevel.Fatal:
                    Trace.TraceError(string.Format("FATAL : {0}", message));
                    return;
            }
        }
    }

**Comment by s093294** [comment]
Heres what I came up with:

    var logProvider = new MultiDiagnosticsTraceLogProvider();
    LogProvider.SetCurrentLogProvider(logProvider);
    SInnovations.ConfigurationManager.Logging.LogProvider.SetCurrentLogProvider(logProvider);
            SInnovations.Azure.TableStorageRepository.Logging.LogProvider.SetCurrentLogProvider(logProvider);
            SInnovations.Azure.MessageProcessor.Core.Logging.LogProvider.SetCurrentLogProvider(logProvider);


    public class MultiTargetDiagnosticsTraceLogger : DiagnosticsTraceLogger
    {
        public MultiTargetDiagnosticsTraceLogger(string name)
            : base(name)
        {

        }
        public bool Log(SInnovations.ConfigurationManager.Logging.LogLevel logLevel, Func<string> messageFunc, Exception exception = null, params object[] formatParameters)
        {
            return Log((Ascend.Common.Logging.LogLevel)(int)logLevel, messageFunc, exception, formatParameters);
        }
        public bool Log(SInnovations.Azure.MessageProcessor.Core.Logging.LogLevel logLevel, Func<string> messageFunc, Exception exception = null, params object[] formatParameters)
        {
            return Log((Ascend.Common.Logging.LogLevel)(int)logLevel, messageFunc, exception, formatParameters);
        }
        public bool Log(SInnovations.Azure.TableStorageRepository.Logging.LogLevel logLevel, Func<string> messageFunc, Exception exception = null, params object[] formatParameters)
        {
            return Log((Ascend.Common.Logging.LogLevel)(int)logLevel, messageFunc, exception, formatParameters);
        }
    }

**Comment by damianh** [comment]
Nice.

Should this go into the wiki?

(closing the issue because there is nothing that needs to change on the liblog side; let me know if you disagree)
