### ISSUE TITLE
log4net LogicalThreadContext support

### ISSUE THREAD

**Issue by darkl** [damianh/LibLog#80]
This is somehow related to #49 I've opened before.

log4net's [NDC](https://github.com/apache/log4net/blob/782e8267dc44a3db5e0b095c91c1de76a37a9e9b/src/log4net/NDC.cs) and [MDC](https://github.com/apache/log4net/blob/782e8267dc44a3db5e0b095c91c1de76a37a9e9b/src/log4net/MDC.cs) classes which are used by LibLog use the ThreadContext static class (see the implementation).
ThreadContext is implemented using a [ThreadStatic] variable. This doesn't work well with the asyc/await feature since you might return to a different thread than the one you started on.

In order to solve this, we can use log4net's [LogicalThreadContext](https://github.com/apache/log4net/blob/782e8267dc44a3db5e0b095c91c1de76a37a9e9b/src/log4net/LogicalThreadContext.cs) - we just need to use the exact same implementation in the referenced NDC and MDC files, but replace everywhere ThreadContext with LogicalThreadContext.
This will use the CallContext class and therefore will not suffer with async/await issues.

Note that this is the default behavior of Serilog's implementation (see [here](http://nblumhardt.com/2013/09/serilog-gets-a-diagnostic-context/)).

**Comment by damianh** [comment]
Fixed via #81

**Comment by damianh** [comment]
4.2.5 up on nuget.org
