### ISSUE TITLE
Should LibLog support password masking scenarios

### ISSUE THREAD

**Issue by dealproc** [damianh/LibLog#83]
As my library is developing, i'm running into an issue that i do not think i want the users of the library to have to implement... password masking.

In my case, it could be a json string or a connectionString, like you would use for SQL server.

Digging into the source code, it looks like the most practical place to implement the masking would be under `LogMessageFormatter.SimulateStructuredLogging(messageFunc, formatParameters) {...}`, and then in the serilog provider `{TBD}`.

I have some code that could be a basis of this, if interested (regex may need to be refactored a slight bit, but it is functional).

**Comment by damianh** [comment]
No, LibLog should not be doing this. I don't think it's even a logging framework concern. This is something you need to control in your application.

**Comment by damianh** [comment]
[150906_Law_Trials.pdf](https://github.com/damianh/LibLog/files/7214/150906_Law_Trials.pdf)
