### ISSUE TITLE
XML Documentation

### ISSUE THREAD

**Issue by StevenBonePgh** [damianh/LibLog#84]
When generating documentation using Sandcastle Help File Builder after installing the LibLog.cs, I noticed there were a few missing doc comments.  One was on the Logger delegate, the other is a missing Namespace comment.

I'd suggest adding something like this for the namespace comment - adding the version like in the sample would be great (if possible):
    /// `<summary>`
    /// Logging mechanism provided by using `<see href="https://github.com/damianh/LibLog">LibLog</see>` version 4.2.3. For documentation on how
    /// to use, configure, or modify logging in this library, visit the `<see href="https://github.com/damianh/LibLog">LibLog Project Site</see>`.
    /// `</summary>`
    [CompilerGenerated]
    internal class NamespaceDoc
    {
    }

Great library!

**Comment by damianh** [comment]
Closing because of age. If still desired a quick PR would be appreciated.

> Great library!

Cheers!
