### ISSUE TITLE
CA1065 Analysis Issues

### ISSUE THREAD

**Issue by dealproc** [damianh/LibLog#85]
Running code analysis on a solution that is implementing LibLog is bringing up CA1065 because the internal classes (e.g. `internal class SerilogLogger`) is throwing an exception during static construction.  According to the dialog:

'SerilogLogProvider.SerilogLogger.SerilogLogger()' creates an exception of type 'InvalidOperationException'. Exceptions should not be raised in this type of method. If this exception instance might be raised, change this method's logic so it no longer raises an exception.

Would it be better if we annotate the liblog code with a suppression for this exception, or is there a way to follow the suggestion here and refactor the static constructor to not need to throw an exception?

**Comment by damianh** [comment]
I might have a look at how this is activated instead, i.e. not be exception based. (vs fixing the CA1065).

Thanks for reporting :)

(Sorry for delay, my OSS work is not getting any time lately)

**Comment by dealproc** [comment]
sure, no worries.

**Comment by adamralph** [comment]
This is fixed by #89

**Comment by damianh** [comment]
Thanls @adamralph

**Comment by adamralph** [comment]
@damianh this issue is on the 5.0.0 milestone but the PR which fixes it is on 4.2.4. Which one should it be?

**Comment by damianh** [comment]
4.2.4 Fixed
