### ISSUE TITLE
Does using OpenNestedContext/OpenMappedContext require explicit SetCurrentLogProvider() call?

### ISSUE THREAD

**Issue by mthierba** [damianh/LibLog#96]
I've noticed that both, `OpenNestedContext()` and `OpenMappedContext()`, return a no-op if `CurrentLogProvider` is null. The latter, however, only ever gets set by calling `LogProvider.SetCurrentLogProvider()` explicitly. Hence, if I've got code like the example from the Wiki in my library:

```
public class MyClass
{
    private static readonly ILog Logger = LogProvider.For<MyClass>(); 

    public MyClass()
    {
        using(LogProvider.OpenNestedContext("message"))
        using(LogProvider.OpenMappedContext("key", "value"))
        {
            Logger.Info(....);
        }
    }
}
```

... the `OpenXXXContext` calls are simply being ignored. I'm wondering now what the suggested usage pattern is. Am I supposed to put a line like this in some init code of my library?

```
LogProvider.SetCurrentLogProvider(LogProvider.ResolveLogProvider());
```

I would have expected that `CurrentLogProvider` was set implicitly the first time `ResolveLogProvider()` gets called. Am I completely misunderstanding something?

I've come across this when I was using a LibLog-enabled library from a log4net client which used a "[%property{NDC}]" conversion pattern - which, however, always returned "[(null)]" until I added the explicit call to `SetCurrentLogProvider()` above to the library.

If this is how I am supposed to use LibLog, that's okay, but I didn't find it very intuitive and think it should be documented.

**Comment by iangriffin** [comment]
Thanks for posting this, I was trying to track down why `OpenNestedContext` and `OpenMappedContext` weren't actually doing anything (with Serilog). I think the documentation should reflect the actual usage pattern. Maybe the pattern should change.

**Comment by martijnburgers** [comment]
Thanks for posting @mthierba. I've been through the same journey. It wouldn't be very intuitive to use init code inside the lib or setting the log provider for all consumed libs that that uses `LibLog`. 

The problem is very clear but I have created some [repro code](https://github.com/martijnburgers/LibLogTryOut) for the sake of it.

I also wrote a passing test for an altered version of `LibLog` where I changed the implementations of `OpenNestedContext` \ `OpenMappedContext` to:

```csharp
static IDisposable OpenNestedContext(string message)
{
	ILogProvider logProvider = CurrentLogProvider ?? ResolveLogProvider();

	return logProvider == null 
		? new DisposableAction(() => {}) 
		: logProvider.OpenNestedContext(message);
}

static IDisposable OpenMappedContext(string key, string value)
{
	ILogProvider logProvider = CurrentLogProvider ?? ResolveLogProvider();

	return logProvider == null 
		? new DisposableAction(() => { }) 
		: logProvider.OpenMappedContext(key, value);
}
```

**Comment by damianh** [comment]
@martijnburgers I've incorporated your suggestion. Thank you!

4.2.5 up on nuget.org

**Comment by martijnburgers** [comment]
@damianh Great!!!

**Comment by damianh** [comment]
No problem. :)

Sorry for the slow responses on this. Under *a lot* of work at this last
few months.

**Comment by mthierba** [comment]
@damianh Thanks a lot for this!

**Comment by martijnburgers** [comment]
@damianh no worries :-)
