### ISSUE TITLE
LibLog is logging it's own Stack Trace and not the actual log

### ISSUE THREAD

**Issue by Shachar1** [damianh/LibLog#97]
When I log data in my application and I want the Method Name and Class Name I'm getting the LibLog data and not my application data - Method Name = Log , and Class Name = LoggerExecutionWrapper.

After some debugging it seems that the problem is in the IsInTypeHierarchy method(line 1213) which returns the wrong result so the Stack Trace includes the LibLog data. 
I wrote my own method to check if the types in the Stack Trace are part of the LibLog namespace, if so, I'm creating a new Stack Trace without them.

I'm using LibLog 4.2 + log4net

Thanks

**Comment by damianh** [comment]
Can you share the code to you solution please? 

A problem with getting the MethodName + ClassName is that compiler and JIT optimizations (inlining) can often create different stack traces at runtime which is why I recommend not doing this sort of thing.

**Comment by Shachar1** [comment]
Hey Damian, 

This is the function I've added before the - IsInTypeHierarchy. 
I'm getting the result and calling a new StackTrace with the result.

            private int RemoveLogNamespaceFromStackTrace(StackTrace stack) 
            {
                StackFrame sd = new StackFrame();
                bool found = false;
                Type thisType = GetType();
                var types = AppDomain.CurrentDomain.GetAssemblies()
                            .SelectMany(t => t.GetTypes())
                            .Where(t => t.IsClass && t.Namespace == thisType.Namespace).ToList();
                int index = 0;
                for (index = 0; index < stack.FrameCount; index++) 
                {
                    if (!types.Contains(stack.GetFrame(index).GetMethod().DeclaringType)) 
                    {
                        break;    
                    }
                }

                return index;
            }

**Comment by phatcher** [comment]
@Shachar1  I'm trying to use LibLog 4.2.6 and getting the same but can you explain a bit more please and provide the calling code as well.

@damianh  Log4Net manages it quite handily and without this I think this limits the possibility of adoption of the library.

**Comment by phatcher** [comment]
Given that we are going to be in the <ProjectName>.Logging.xxx namespace, presume that anything in <ProjectName>.Logging isn't the real call site, so we get something like this...
```
                    lock (CallerStackBoundaryTypeSync)
                    {
#if !LIBLOG_PORTABLE
                        StackTrace stack = new StackTrace();
                        Type thisType = GetType();
                        Debug.WriteLine("We are in " + thisType.FullName);
                        var prefix = LoggingNamespace(thisType);
                        s_callerStackBoundaryType = Type.GetType("LoggerExecutionWrapper");
                        for (var i = 1; i < stack.FrameCount; i++)
                        {
                            var frame = stack.GetFrame(i);
                            var method = frame.GetMethod();
                            var declType = method.DeclaringType;

                            Debug.WriteLine(i + ":" + declType + "." + method.Name);
                            if (!IsInTypeHierarchy(thisType, declType) && (string.IsNullOrEmpty(prefix) || !declType.Namespace.StartsWith(prefix)))
                            {
                                Debug.WriteLine("Using " + frame.GetMethod().DeclaringType);
                                s_callerStackBoundaryType = stack.GetFrame(i - 1).GetMethod().DeclaringType;
                                break;
                            }
                        }
#else
                        s_callerStackBoundaryType = typeof (LoggerExecutionWrapper);
#endif
                    }
                }
```
The additional function is 
```
            private string LoggingNamespace(Type type)
            {
                var ns = type.Namespace;
                var posn = ns.IndexOf(".Logging");
                int index = 0;
                if (posn > -1)
                {
                    // Include the logging in the exclude
                    return ns.Substring(0, posn + 8);
                }

                return string.Empty;                
            }
```
Avoids an expensive type search and has the advantage is if you write any extension methods, if you put them in the <Project>.Logging namespace they'll be excluded as well
