### ISSUE TITLE
Resolving logger in unit tests

### ISSUE THREAD

**Issue by jlegan** [damianh/LibLog#98]
I came across an interesting scenario tonight when a unit test was failing on the build server (teamcity) and I did not have an easy way to track it down. The unit test failure was occurring in a library that is consumed by several larger project each of which use SeriLog as their primary logger. We produce our own internal nuget packages and each lib uses LibLog heavily for everything from trace to exception logging which works great.

I had never thought of writing up a logger in a unit test but I know that NUnit will display console.writeline content in its output so I thought this would be an easy way to track down the bug. I added SeriLog to the NUnit test project, created a console logger (two lines of code) with a minimum logging level of Verbose and ran the test locally. I was surprised to not see any output. To test it I added some output using the logger to a setup and teardown method and those were logging correctly to the NUnit test output. I then spent the next few hours trying get the logger to resolve correctly within a unit test session. 

This is clearly not a liblog problem however if anyone is going to know how to do this outside of introducing a container or singleton to the test I suspect it would be this group. Does anyone have any insight on how to get the standard private readonly static logger which exists everywhere in code to resolve the logger which is initialized in the unit test through the standard GetCurrentClassLogger?

**Comment by damianh** [comment]
I use xunit for tests and I know that capturing test output is a different process http://dhickey.ie/2015/06/capturing-log-output-in-tests-with-xunit2/ . I haven't use NUnit is a long time, is this a similar problem?

**Comment by damianh** [comment]
@jlegan Did you get a solution to your problem? Did my blog post help you in any way?

(Closing this unless there it is determined there is an issue with LibLog. ty).
